project:
  type: manuscript
  output-dir: docs

manuscript:
  resources:
    - data/metric_types.xlsx

website:
  title: "Multi-country comparison of light exposure-related behaviour"
  site-url: https://tscnlab.github.io/ZaunerEtAl_NatHumBehav_2026
  repo-url: https://github.com/tscnlab/ZaunerEtAl_NatHumBehav_2026/
  issue-url: https://github.com/tscnlab/ZaunerEtAl_NatHumBehav_2026/issues
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  navbar:
    left:
      - href: index.qmd
        text: Manuscript
      - href: https://github.com/MeLiDosProject
        text: Data source
      - href: descriptives.qmd
        text: "Descriptive summaries"
      - href: RQ1.qmd
        text: "RQ1: environmental effects"
      - href: RQ2.qmd
        text: "RQ2: behavioural effects"
      - href: RQ3.qmd
        text: "RQ3: individual effects"
      - href: data_preparation.qmd
        text: "Data preparation"
      - href: metric_preparation.qmd
        text: "Metric preparation"
      - href: deviations.qmd
        text: "Preregistration deviations"
      - text: "License"
        href: LICENSE.md
    right:
      - icon: github
        href: https://github.com/tscnlab/ZaunerEtAl_NatHumBehav_2026
        aria-label: Quarto GitHub


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    link-external-newwindow: true
    toc: true
    comments:
      hypothesis: true
    format:
    code-link: true
    code-line-numbers: true
    toc-location: left
    toc-depth: 3
    toc-expand: 2
  # typst:
  #   toc: true
  #   toc-depth: 3
  #   number-sections: true
  #   papersize: a4
  #   fig-format: png
  #   fig-dpi: 600
  #   fig-height: 3.45
format-links:
  - html
  # - format: typst
  #   text: PDF
  #   icon: file-pdf

date: last-modified

language:
  title-block-published: "Last modified:"

execute:
  warning: false
  error: false
  echo: true
  freeze: auto
