stopifnot(as.character(getRversion()) == "4.6.1")
root <- "/private/tmp/ba018-diagnostic-bookkeeping-review.zoYV0w"
stage2 <- "/Users/zauner/.codex/worktrees/82ab/ZaunerEtAl_bioRxiv_2026/audit/analyses/brown_adherence/main_linkage_b_amendment/stage2"
owner <- file.path(stage2, "completion_v2/continued_final_package_003")
sha <- function(p) unname(digest::digest(p, algo = "sha256", file = TRUE))
manifest_path <- file.path(owner, "final_manifest.csv")
stopifnot(sha(manifest_path) == "ef06de7af67271cfdd2b6ab4958aede173e5707d1a5d6c8c20f23f63db4877fe")
x <- read.csv(manifest_path, stringsAsFactors = FALSE)
stopifnot(!anyDuplicated(x$path), !manifest_path %in% x$path)
x$current_sha256 <- vapply(x$path, sha, character(1))
x$current_bytes <- unname(file.info(x$path)$size)
x$current_exact <- x$current_sha256 == x$sha256 & x$current_bytes == x$bytes
stopifnot(all(x$current_exact))
write.csv(x, file.path(root, "owner_manifest_verification.csv"), row.names = FALSE)
jobs <- list.files(file.path(stage2, "preflight/execution_jobs"), recursive = TRUE, full.names = TRUE, pattern = "^finish\\.json$")
j <- lapply(jobs, jsonlite::fromJSON)
stopifnot(length(j) == 8L, sum(vapply(j, function(v) v$exit_code != 0, logical(1))) == 3L, all(vapply(j, function(v) !v$timed_out && v$child_reaped, logical(1))))
used <- sum(vapply(j, function(v) v$elapsed_seconds, numeric(1)))
draws <- read.csv(file.path(owner, "diagnostic_draw_accounting.csv"), stringsAsFactors = FALSE)
stopifnot(nrow(draws) == 6L, sum(draws$attempted_draws) == 250L, sum(draws$durably_exported_draws) == 0L, !dir.exists(file.path(stage2, "diagnostics")), !file.exists(file.path(stage2, "preflight/computation.lock")))
protection <- read.csv(file.path(owner, "protected_identity_verification.csv"), stringsAsFactors = FALSE)
protection <- protection[!duplicated(protection$path), c("path", "expected_sha256", "expected_bytes")]
protection$current_sha256 <- vapply(protection$path, sha, character(1))
protection$current_bytes <- unname(file.info(protection$path)$size)
protection$current_exact <- with(protection, expected_sha256 == current_sha256 & expected_bytes == current_bytes)
stopifnot(all(protection$current_exact))
write.csv(protection, file.path(root, "protected_verification.csv"), row.names = FALSE)
f <- read.csv(file.path(owner, "finalization_checks.csv"), stringsAsFactors = FALSE)
stopifnot(all(f$pass))
scope <- data.frame(owner_members = nrow(x), protected_unique = nrow(protection), finalization_checks = nrow(f), jobs = length(j), stopped_jobs = 3L, cumulative_seconds = used, attempted_draws = 250L, exported_draws = 0L, current_retry_authorized = FALSE)
write.csv(scope, file.path(root, "independent_stop_summary.csv"), row.names = FALSE)
cat(sprintf("BROWN_DIAGNOSTIC_STOP=VERIFIED owner=%s protected=%s finalization=%s jobs=8 seconds=%.15f attempted_draws=250 exported_draws=0 retry=HELD\n", nrow(x), nrow(protection), nrow(f), used))
