stopifnot(as.character(getRversion()) == "4.6.1")
author <- "/Users/zauner/Documents/Arbeit/12-TUM/MeLiDos/WP2.2.5_Data_Analysis/ZaunerEtAl_bioRxiv_2026"
brown <- "/Users/zauner/.codex/worktrees/82ab/ZaunerEtAl_bioRxiv_2026"
stage1 <- file.path(brown, "audit/analyses/brown_adherence/main_linkage_b_amendment/stage1")
stage2 <- file.path(brown, "audit/analyses/brown_adherence/main_linkage_b_amendment/stage2")
scratch <- "/private/tmp/ba018-qualified-continuation.sCpljO"
relative_root <- "audit/decisions/brown_main_linkage_b_stage2_qualified_diagnostics_continuation_001"
root <- file.path(author, relative_root)
archive <- file.path(root, "independent_preflight")
sha <- function(p) unname(digest::digest(p, algo = "sha256", file = TRUE))
stopifnot(!dir.exists(archive), !file.exists(file.path(root, "dispatch_manifest.csv")))
dir.create(archive)
files <- list.files(scratch, full.names = TRUE, recursive = FALSE, all.files = TRUE, no.. = TRUE)
files <- files[!file.info(files)$isdir]
stopifnot(all(file.copy(files, archive, overwrite = FALSE, copy.mode = TRUE, copy.date = TRUE)))
copied <- file.path(archive, basename(files))
stopifnot(identical(unname(vapply(files, sha, character(1))), unname(vapply(copied, sha, character(1)))))
ic <- read.csv(file.path(archive, "independent_checks.csv"), stringsAsFactors = FALSE)
sc <- read.csv(file.path(archive, "supervisor_checks.csv"), stringsAsFactors = FALSE)
stopifnot(nrow(ic) == 20L, all(ic$pass), nrow(sc) == 33L, all(sc$pass == "True"))
owner_path <- file.path(stage2, "completion_v2/continued_final_package_002/final_manifest.csv")
owner <- read.csv(owner_path, stringsAsFactors = FALSE)
central_path <- file.path(author, "audit/decisions/brown_main_linkage_b_stage2_m1_coverage_gate_stop_001/independent_manifest.csv")
central <- read.csv(central_path, stringsAsFactors = FALSE)
central_files <- ifelse(startsWith(central$path, "/"), central$path, file.path(author, central$path))
stopifnot(all(vapply(owner$path, sha, character(1)) == owner$sha256), all(file.info(owner$path)$size == owner$bytes))
stopifnot(all(vapply(central_files, sha, character(1)) == central$sha256), all(file.info(central_files)$size == central$bytes))
protected <- read.csv(file.path(archive, "protected_2287_verification.csv"), stringsAsFactors = FALSE)
stopifnot(all(vapply(protected$path, sha, character(1)) == protected$expected_sha256))
stage1_manifest <- file.path(stage1, "final_manifest.csv")
stopifnot(sha(stage1_manifest) == "7290ad5f2e595949cde38dcd241bc5f4cb0037094c1a0ed99e03c3252e877dc0")
s1 <- read.csv(stage1_manifest, stringsAsFactors = FALSE)
stopifnot(nrow(s1) == 89L, !anyDuplicated(s1$path))
s1_paths <- ifelse(startsWith(s1$path, "/"), s1$path, file.path(brown, s1$path))
stopifnot(all(vapply(s1_paths, sha, character(1)) == s1$sha256))
held_paths <- c(file.path(stage2, "code/run_bounded_job_v3.py"), file.path(stage2, "completion_v2/continued_final_package_003"), file.path(stage2, "preflight/computation.lock"))
stopifnot(!any(file.exists(held_paths)))
rules <- c("plan.md", "prospective_model_jobs.csv", "prospective_conditional_fit_reserves.csv", "prospective_diagnostic_draw_budget.csv", "prospective_stage2_output_contract.csv", "formula_registry.csv", "planned_sensitivity_support.csv", "accepted_model_library_pins.csv")
paths <- unique(c(list.files(root, recursive = TRUE, full.names = TRUE, all.files = TRUE, no.. = TRUE), owner_path, owner$path, central_path, central_files, stage1_manifest, file.path(stage1, rules), file.path(author, "audit/decisions/brown_adherence_main_linkage_b_stage2_transition.md")))
stopifnot(all(file.exists(paths)), !any(file.info(paths)$isdir), !anyDuplicated(paths))
manifest <- data.frame(path = paths, sha256 = vapply(paths, sha, character(1)), bytes = unname(file.info(paths)$size))
manifest <- manifest[order(manifest$path), ]
stopifnot(!file.path(root, "dispatch_manifest.csv") %in% manifest$path)
write.csv(manifest, file.path(root, "dispatch_manifest.csv"), row.names = FALSE)
replay <- read.csv(file.path(root, "dispatch_manifest.csv"), stringsAsFactors = FALSE)
stopifnot(!anyDuplicated(replay$path), all(vapply(replay$path, sha, character(1)) == replay$sha256), all(file.info(replay$path)$size == replay$bytes))
verification <- data.frame(check = c("independent_readonly", "mocked_supervisor", "owner_stop", "central_stop", "protected", "stage1", "dispatch_unique_noncircular"), pass = TRUE, members = c(20L, 33L, 182L, 198L, 2287L, 89L, nrow(replay)))
write.csv(verification, file.path(root, "dispatch_verification.csv"), row.names = FALSE)
cat(sprintf("BA018_QUALIFIED_CONTINUATION_SEAL=PASS rows=%s decision=%s dispatch=%s supervisor=%s\n", nrow(manifest), sha(file.path(root, "decision.md")), sha(file.path(root, "dispatch_manifest.csv")), sha(file.path(archive, "run_bounded_job_v3.py"))))
