stopifnot(as.character(getRversion())=="4.6.1")
library(xml2);library(jsonlite);library(digest)
c<-file.path(getwd(),"audit/manuscript_nature_health/final_format_completion_2026_09_14")
p<-file.path(getwd(),"audit/manuscript_nature_health/final_review_production_2026_09_14")
f<-file.path(c,"inputs/prior_integrated.html")
stopifnot(digest(f,file=TRUE,algo="sha256")=="0488130aba3ef7b043c743ee879d6e88f9c2ece8ae3c0c2eba89d90e116ea510")
visible<-function(n){if(xml_type(n)=="text")return(xml_text(n));if(xml_name(n)=="br")return(" ");paste0(vapply(xml_contents(n),visible,character(1)),collapse="")}
norm<-function(x)trimws(gsub("[[:space:]\u00a0]+"," ",x))
d<-read_html(f);tabs<-xml_find_all(d,"//table[contains(concat(' ',normalize-space(@class),' '),' gt_table ')]")
old<-read.csv(file.path(p,"evidence/html_ordered_cells_round2.csv"));labels<-unique(old$label)
stopifnot(length(tabs)==19L,length(labels)==19L)
all<-lapply(seq_along(tabs),function(i){n<-xml_find_all(tabs[[i]],"./thead/tr/*[self::th or self::td]|./tbody/tr/*[self::th or self::td]|./tfoot/tr/*[self::th or self::td]");texts<-norm(vapply(n,visible,character(1)));target<-old$text[old$label==labels[i]];if(labels[i]=="Table_S12")texts2<-texts[nzchar(texts)]else texts2<-texts; if(labels[i]=="Table_S12")target<-target[nzchar(target)];stopifnot(identical(texts2,target));list(label=labels[i],cells=texts)})
stopifnot(sum(vapply(all[c(2,5,6)],function(x)length(x$cells),integer(1)))==413L)
write_json(all,file.path(c,"evidence/html_expected_cells.json"),auto_unbox=TRUE,pretty=TRUE)
writeLines(capture.output(sessionInfo()),file.path(c,"evidence/html_preflight_R_session.txt"))
cat('PASS: all 19 table cell fingerprints; 413 targeted cells exact before transformation\n')
