stopifnot(as.character(getRversion()) == "4.6.1")
suppressPackageStartupMessages(library(digest))
root <- normalizePath(getwd())
prior <- file.path(root, "audit/manuscript_nature_health/final_review_production_2026_09_14")
out <- file.path(root, "audit/manuscript_nature_health/final_format_completion_2026_09_14")
sha <- function(f) digest(f, file=TRUE, algo="sha256")
dispatch <- file.path(root, "audit/report_harmonization/final_documents_2026_09_13/writer_format_completion_order_010b_dispatch_manifest.csv")
stopifnot(sha(dispatch)=="26e9b4fbe415e61c3a818286b397999c7f0411dd6c2877787b1ca153980562b1")
d <- read.csv(dispatch)
resolve <- function(x) ifelse(startsWith(x,"/"),x,file.path(root,x))
d$actual_sha256 <- vapply(resolve(d$path),sha,character(1))
stopifnot(nrow(d)==60L,!anyDuplicated(d$path),identical(d$sha256,d$actual_sha256))
manifest <- file.path(prior,"candidate_package_manifest.csv")
stopifnot(sha(manifest)=="624753fabeb69a47cc9fe7262cba25849963e8ab8aca201512f47fbb5ec65b32")
m <- read.csv(manifest)
m$actual_sha256 <- vapply(file.path(prior,m$path),sha,character(1))
stopifnot(nrow(m)==439L,identical(m$sha256,m$actual_sha256))
dir.create(file.path(out,"evidence"),showWarnings=FALSE,recursive=TRUE)
write.csv(d,file.path(out,"evidence/dispatch_preflight.csv"),row.names=FALSE)
write.csv(m,file.path(out,"evidence/prior439_preflight.csv"),row.names=FALSE)
writeLines(capture.output(sessionInfo()),file.path(out,"evidence/preflight_R_session.txt"))
cat("PASS: R",as.character(getRversion()),"60 dispatch and 439 prior package pins exact\n")
