stopifnot(as.character(getRversion())=="4.6.1")
suppressPackageStartupMessages({library(xml2);library(jsonlite);library(digest)})
root<-normalizePath(getwd());c<-file.path(root,"audit/manuscript_nature_health/final_format_completion_2026_09_14");p<-file.path(root,"audit/manuscript_nature_health/final_review_production_2026_09_14")
sha<-function(f)digest(f,file=TRUE,algo="sha256");checks<-list()
check<-function(id,pass,detail="")checks[[length(checks)+1L]]<<-data.frame(id=id,pass=isTRUE(pass),detail=detail)
docx<-file.path(c,"deliverables/Nature_Health_manuscript_round2.docx")
ns<-c(w="http://schemas.openxmlformats.org/wordprocessingml/2006/main",wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing",a="http://schemas.openxmlformats.org/drawingml/2006/main",r="http://schemas.openxmlformats.org/officeDocument/2006/relationships")
d<-read_xml(unz(docx,"word/document.xml"));old<-read_xml(unz(file.path(c,"inputs/prior_main.docx"),"word/document.xml"))
check("all_Word_text_runs_exact_order",identical(xml_text(xml_find_all(d,"//w:t",ns)),xml_text(xml_find_all(old,"//w:t",ns))))
paras<-xml_find_all(d,"//w:body/w:p",ns);styles<-xml_attr(xml_find_first(paras,"./w:pPr/w:pStyle",ns),"val")
pt<-vapply(paras,function(x)paste0(xml_text(xml_find_all(x,".//w:t",ns)),collapse=""),character(1))
oldparas<-xml_find_all(old,"//w:body/w:p",ns);oldstyles<-xml_attr(xml_find_first(oldparas,"./w:pPr/w:pStyle",ns),"val")
h<-paras[!is.na(styles)&styles=="berschrift1"]
ht<-vapply(h,function(x)paste0(xml_text(xml_find_all(x,".//w:t",ns)),collapse=""),character(1))
check("13_major_headings",identical(ht,c("Abstract","Introduction","Results","Discussion","Methods","Data availability","Code availability","References","Acknowledgements","Funding","Author contributions","Competing interests","Supplementary Information")))
check("13_page_starts",length(h)==13L&&all(!is.na(xml_name(xml_find_first(h,"./w:pPr/w:pageBreakBefore",ns)))))
check("93_reference_paragraphs",sum(styles=="Literaturverzeichnis",na.rm=TRUE)==93L)
check("28_author_14_affiliation_block_exact",sum(styles=="Author",na.rm=TRUE)==1L&&identical(xml_text(xml_find_all(d,"//w:p[w:pPr/w:pStyle[@w:val='Author']]",ns)),xml_text(xml_find_all(old,"//w:p[w:pPr/w:pStyle[@w:val='Author']]",ns))))
check("AI_statement_and_all_declarations_retained",any(grepl("artificial intelligence|AI-assisted|AI assistance|generative AI",pt,ignore.case=TRUE)))
check("54_drawings_no_floats_no_main_native_tables",length(xml_find_all(d,"//wp:inline",ns))==54L&&length(xml_find_all(d,"//wp:anchor|//w:body/w:tbl",ns))==0L)
members<-unzip(docx,list=TRUE)
zipsha<-function(name){con<-unz(docx,name,"rb");on.exit(close(con));digest(readBin(con,"raw",n=members$Length[match(name,members$Name)]),algo="sha256",serialize=FALSE)}
rels<-read_xml(unz(docx,"word/_rels/document.xml.rels"));rn<-xml_find_all(rels,"//*[local-name()='Relationship']");rm<-setNames(xml_attr(rn,"Target"),xml_attr(rn,"Id"))
draws<-xml_find_all(d,"//wp:inline",ns)
targets<-vapply(draws,function(x){ids<-unique(xml_attr(xml_find_all(x,".//*[@r:embed]",xml_ns(d)),"embed"));stopifnot(length(ids)==1L);paste0("word/",unname(rm[ids]))},character(1))
tables<-fromJSON(file.path(c,"maps/word_table_png_manifest.json"),simplifyVector=FALSE);parts<-unlist(lapply(tables,`[[`,"files"),recursive=FALSE)
check("19_table_keys_30_parts",length(tables)==19L&&length(parts)==30L)
pngs<-targets[grepl("[.]png$",targets)];check("30_visible_PNGs_exact_in_order",length(pngs)==30L&&identical(unname(vapply(pngs,zipsha,character(1))),unname(vapply(parts,`[[`,character(1),"sha256"))))
for(x in parts)check(paste0("PNG_source_",basename(x$path)),sha(x$path)==x$sha256)
check("17_original_unused_density_payloads_retained",length(setdiff(members$Name[grepl("^word/media/.*[.]png$",members$Name)],pngs))==17L)
oldparts<-unlist(lapply(fromJSON(file.path(p,"maps/word_table_png_manifest.json"),simplifyVector=FALSE),`[[`,"files"),recursive=FALSE)
differences<-vapply(seq_along(parts),function(i)parts[[i]]$sha256!=oldparts[[i]]$sha256,logical(1));check("only_S3_PNG_changed",sum(differences)==1L&&basename(parts[[which(differences)]]$path)=="supp_table_s3_part_01.png")
embed<-fromJSON(file.path(c,"evidence/svg_integration_round2.json"),simplifyVector=FALSE)
check("23_SVG_sources_24_appearances",length(embed$embedded_svgs)==23L&&sum(grepl("[.]svg$",targets))==24L)
for(x in embed$embedded_svgs)check(paste0("SVG_",x$word_label),sha(x$path)==x$sha256&&zipsha(x$embedded_part)==x$sha256)
oldfigs<-fromJSON(file.path(p,"maps/expanded_svg_manifest.json"),simplifyVector=FALSE)$accepted_figures
newfigs<-fromJSON(file.path(c,"maps/expanded_svg_manifest.json"),simplifyVector=FALSE)$accepted_figures
changed<-vapply(seq_along(newfigs),function(i)newfigs[[i]]$sha256!=oldfigs[[i]]$sha256,logical(1));check("only_accepted_S15B_SVG_changed",sum(changed)==1L&&newfigs[[which(changed)]]$word_label=="Supplementary Figure S15B")
crop<-function(doc){vapply(xml_find_all(doc,"//*[local-name()='srcRect']"),as.character,character(1))}
check("S8_crop_boundaries_exact",identical(crop(d),crop(old)))
nf<-list.files(file.path(c,"editable_tables"),pattern="[.]docx$",full.names=TRUE)
native<-data.frame(file=basename(nf),sha256=vapply(nf,sha,character(1)),prior_sha256=vapply(file.path(p,"editable_tables/round2",basename(nf)),sha,character(1)))
check("19_native_tables_byte_exact",nrow(native)==19L&&all(native$sha256==native$prior_sha256));write.csv(native,file.path(c,"evidence/native19_identity.csv"),row.names=FALSE)
htmlfile<-file.path(c,"project/html_round2/ZaunerEtAl2026_NatHealth_phase3_brown.html");hd<-read_html(htmlfile);ot<-read_html(file.path(c,"inputs/prior_integrated.html"))
visible<-function(n){if(xml_type(n)=="text")return(xml_text(n));if(xml_name(n)=="br")return(" ");paste0(vapply(xml_contents(n),visible,character(1)),collapse="")}
norm<-function(x)trimws(gsub("[[:space:]\u00a0]+"," ",x))
tabs<-xml_find_all(hd,"//table[contains(concat(' ',normalize-space(@class),' '),' gt_table ')]");expected<-fromJSON(file.path(c,"evidence/html_expected_cells.json"),simplifyVector=FALSE)
check("HTML_19_tables",length(tabs)==19L)
for(i in seq_along(tabs)){n<-xml_find_all(tabs[[i]],"./thead/tr/*|./tbody/tr/*|./tfoot/tr/*");check(paste0('HTML_cells_',expected[[i]]$label),identical(norm(vapply(n,visible,character(1))),unlist(expected[[i]]$cells)))}
for(x in list(list('nh_table2_primary',c(176,254,230,180,180,200,100)),list('near-eye-metric-summary',c(210,86,138,146,146,154,138,146,138,146,138,130,120,252)))){cols<-xml_find_all(hd,paste0("//*[@id='",x[[1]],"']//table/colgroup/col"));v<-as.numeric(gsub('[^0-9.]','',xml_attr(cols,'style')));check(paste0('colgroup_',x[[1]]),identical(v,x[[2]]))}
for(x in c("nh_table2_primary","near-eye-metric-summary","recommendation-context")){new<-xml_find_first(hd,paste0("//*[@id='",x,"']//table"));before<-xml_find_first(ot,paste0("//*[@id='",x,"']//table"));for(a in c('id','headers','scope','rowspan','colspan'))check(paste0('semantics_',x,'_',a),identical(xml_attr(xml_find_all(new,'.//*'),a)[!is.na(xml_attr(xml_find_all(new,'.//*'),a))],xml_attr(xml_find_all(before,'.//*'),a)[!is.na(xml_attr(xml_find_all(before,'.//*'),a))]))}
s2<-xml_find_first(hd,"//*[@id='near-eye-metric-summary']//table");s2o<-xml_find_first(ot,"//*[@id='near-eye-metric-summary']//table")
u<-xml_find_all(s2,".//span[@data-whole-mean-sd]");uo<-xml_find_all(s2o,".//span[@data-whole-mean-sd]")
check('170_exact_whole_mean_SD',length(u)==170L&&identical(xml_text(u),xml_text(uo))&&identical(xml_attr(u,'style'),xml_attr(uo,'style')))
di<-xml_attr(xml_find_all(s2,'.//img'),'src');check('17_exact_density_payloads',length(di)==17L&&identical(di,xml_attr(xml_find_all(s2o,'.//img'),'src')))
ids<-xml_attr(xml_find_all(hd,'//*[@id]'),'id');check('unique_HTML_IDs',!anyDuplicated(ids));href<-sub('^#','',xml_attr(xml_find_all(hd,"//a[starts-with(@href,'#')]"),'href'));check('HTML_crossrefs_resolve',all(href%in%ids))
check('HTML_Word_download_exact',sha(file.path(dirname(htmlfile),'ZaunerEtAl2026_NatHealth_phase3_brown.docx'))==sha(docx))
check('HTML_reverse_proof',fromJSON(file.path(c,'evidence/html_packaging_round2.json'))$all_other_bytes_reverse_exactly)
source<-read.csv(file.path(c,'evidence/source_to_copy.csv'));keep<-!endsWith(source$copy,'/helpers/prepare_word_manuscript.py');check('77_staged_static_inputs_exact_one_authorized_helper_edit',nrow(source)==78L&&sum(!keep)==1L&&all(vapply(source$copy[keep],sha,character(1))==source$sha256[keep]))
pre<-read.csv(file.path(c,'evidence/dispatch_preflight.csv'));paths<-ifelse(startsWith(pre$path,'/'),pre$path,file.path(root,pre$path));check('60_dispatch_protected_inputs_unchanged',identical(unname(vapply(paths,sha,character(1))),pre$sha256))
pm<-read.csv(file.path(c,'evidence/prior439_preflight.csv'));check('439_prior_package_immutable',identical(unname(vapply(file.path(p,pm$path),sha,character(1))),pm$sha256))
result<-do.call(rbind,checks);write.csv(result,file.path(c,'evidence/complete_structural_checks.csv'),row.names=FALSE)
writeLines(capture.output(sessionInfo()),file.path(c,'evidence/complete_verification_R_session.txt'))
write_json(list(status=if(all(result$pass))'PASS' else 'FAIL',checks=nrow(result),passed=sum(result$pass),main_sha256=sha(docx),html_sha256=sha(htmlfile),scientific_recalculation=FALSE,visual_review_separate=TRUE),file.path(c,'evidence/structural_summary.json'),auto_unbox=TRUE,pretty=TRUE)
print(result[!result$pass,]);cat(sum(result$pass),'/',nrow(result),'checks passed\n');stopifnot(all(result$pass))
