suppressPackageStartupMessages({library(digest);library(jsonlite)})
stopifnot(as.character(getRversion())=="4.6.1")
central <- "audit/report_harmonization/report018_order72h_mobile_coordination_scroll"
owner <- "audit/manuscript_nature_health/figure_table_selection_svg_revision_2026_09_11"
order <- "audit/report_harmonization/owner_orders/72h_selection_coordination_scroll_recovery.md"
sha <- function(p) digest(p,algo="sha256",file=TRUE,serialize=FALSE)
rows <- function(paths) data.frame(path=paths,sha256=unname(vapply(paths,sha,character(1))),bytes=as.numeric(file.info(paths)$size))
qmd <- "audit/manuscript_nature_health/manuscript_figure_table_selection.qmd"
old_html <- "audit/manuscript_nature_health/manuscript_figure_table_selection.html"
candidate <- file.path(owner,"rendered/manuscript_figure_table_selection.html")
checker <- file.path(owner,"qa/verify_selection_svg_revision.R")
stopifnot(!dir.exists(file.path(owner,"order72h_scroll_recovery")))
stopifnot(!file.exists("audit/manuscript_nature_health/manuscript_figure_table_selection_order72h_candidate.html"))
stopifnot(sha(qmd)=="9acec033d0c24cbb0ee7649c38f55d5cea90052e11b6be7fc5f9e7310890d8f3")
stopifnot(sha(old_html)=="82100e0d3990dec39f61e94970e7a434b02cf94a6d25819ede1be4d24f4130a6")
stopifnot(sha(candidate)=="7688f8ea58e0045fca25c6de971e418b7c6c873dc83f75ed34d942fdcb1c36b4")
stopifnot(sha(checker)=="ef2fd6bf1bd3a3c0a70d8771a8f4da4ea1b96ea86d89e015ddd5cf14337702e9")
old_manifest <- "audit/report_harmonization/report018_order72f_standalone_output_recovery/release_manifest.csv"
stopifnot(sha(old_manifest)=="f12cdca8e7d89fb77336ba2921f0b51701dbf449963501ae89d1d5d8d205f87a")
prior <- read.csv(old_manifest,stringsAsFactors=FALSE)
observed <- rows(prior$path)
changed <- observed$path[observed$sha256!=prior$sha256 | observed$bytes!=prior$bytes]
stopifnot(nrow(prior)==91L,!anyDuplicated(prior$path),identical(changed,checker))
stopifnot(sha(file.path(central,"reconstructed_preqa_verifier.R"))==prior$sha256[prior$path==checker])
replay <- read.csv(file.path(central,"prospective_html_checks.csv"),stringsAsFactors=FALSE)
stopifnot(nrow(replay)==43L,all(replay$pass))
proof <- read.csv(file.path(central,"independent_retained_table_comparison.csv"),stringsAsFactors=FALSE)
stopifnot(nrow(proof)==19L,all(proof$rendered_cell_order_values_exact),all(proof$source_ordered_tokens_exact))
stopifnot(sha(file.path(owner,"qa/visual/loopback_teardown.md"))=="8237ba8822bab44b8224f0de7f8c74b7418770488da0e93821de0839b526575e")
stopifnot(sha(file.path(owner,"qa/verifier_change_chronology.md"))=="38bb5fcc4a05d8045ab2166a0cf75eaeb6007fb035251d5c6d81fdb54d09396a")
listener <- suppressWarnings(system2("lsof",c("-nP","-iTCP:8765","-sTCP:LISTEN"),stdout=TRUE,stderr=TRUE))
stopifnot(length(listener)==0L,identical(attr(listener,"status"),1L))
owner_files <- sort(list.files(owner,recursive=TRUE,all.files=TRUE,no..=TRUE,full.names=TRUE))
owner_files <- owner_files[!dir.exists(owner_files)]
stopifnot(all(!nzchar(Sys.readlink(owner_files))))
write.csv(rows(owner_files),file.path(central,"owner_stopped_inventory.csv"),row.names=FALSE)
pin_paths <- unique(c(prior$path,old_manifest,owner_files,"audit/report_harmonization/report018_order72g_candidate_move_recovery/release_manifest.csv"))
write.csv(rows(pin_paths),file.path(central,"current_execution_pins.csv"),row.names=FALSE)
write.csv(data.frame(path=checker,historical_sha256=prior$sha256[prior$path==checker],observed_sha256=sha(checker),exact_historical_copy=file.path(central,"reconstructed_preqa_verifier.R"),classification="Independently accepted evidence-only checker transition under Order72h; historical release unchanged"),file.path(central,"checker_transition_classification.csv"),row.names=FALSE)
write_json(list(R=as.character(getRversion()),digest=as.character(packageVersion("digest")),xml2=as.character(packageVersion("xml2")),jsonlite=as.character(packageVersion("jsonlite")),time_utc=format(Sys.time(),tz="UTC",usetz=TRUE),checks=43,scope="Temporary source/DOM wrapper simulation only; no project render or visual acceptance",simulated_html_sha256="7055fc384bd845f8b42e3d37901c846060aeef6b8248536dc75240070e7a51e4",listener_probe=list(port=8765,exit=1,output_lines=0),owner_files=length(owner_files)),file.path(central,"replay_and_teardown_context.json"),pretty=TRUE,auto_unbox=TRUE)
stopifnot(file.copy("/private/tmp/order72h-scroll-recovery.rNlIZD/seal.R",file.path(central,"seal_preflight.R"),overwrite=FALSE))
central_files <- list.files(central,recursive=TRUE,all.files=TRUE,no..=TRUE,full.names=TRUE)
central_files <- central_files[!dir.exists(central_files)]
paths <- unique(c(order,pin_paths,central_files))
manifest_path <- file.path(central,"release_manifest.csv")
stopifnot(!file.exists(manifest_path),!manifest_path%in%paths,!anyDuplicated(paths))
manifest <- rows(paths)
write.csv(manifest,manifest_path,row.names=FALSE)
rehashed <- rows(manifest$path)
stopifnot(identical(rehashed,manifest))
print(rows(c(order,manifest_path,file.path(central,"independent_stopped_disposition.md"),file.path(central,"current_execution_pins.csv"))),row.names=FALSE)
cat("ORDER72H_RELEASE=PASS release=",nrow(manifest),"/",nrow(manifest)," current_pins=",length(pin_paths)," owner_stop=",length(owner_files)," prospective=43/43 retained=19/19 prior_release=90/91_plus_exact_checker_classification listener=absent R=4.6.1\n",sep="")
