stopifnot(as.character(getRversion())=="4.6.1")
library(jsonlite);library(digest)
p<-file.path(normalizePath(getwd()),"audit/manuscript_nature_health/final_review_production_2026_09_14")
sha<-function(x)digest(x,file=TRUE,algo="sha256")
old<-fromJSON(file.path(p,"evidence/html_round1_command.json"))
actual<-vapply(names(old$inputs),sha,character(1))
changed<-names(actual)[unname(actual)!=unname(unlist(old$inputs))]
allowed<-file.path(p,c("helpers/prepare_word_manuscript.py","helpers/export_editable_tables.py","helpers/run_stage.py","project/manuscript/R0_NatHealth/manuscript_displays.css","project/audit/manuscript_nature_health/table_layout_visual_corrections_2026_09_14/attempt_02/source/supp_table_s2_complete.html"))
stopifnot(setequal(changed,allowed))
readall<-function(f)readChar(f,file.info(f)$size,useBytes=TRUE)
s2<-readall(allowed[5])
s2<-sub(' id="near-eye-metric-summary" tabindex="0" role="region" aria-label="Supplementary Table S2, full near-eye metric dictionary"',' id="near-eye-metric-summary"',s2,fixed=TRUE)
s2<-sub('id="order009-s2-column-layout"','id="order007-column-layout"',s2,fixed=TRUE)
stopifnot(identical(s2,readall(file.path(p,"evidence/layout_round2_preimages/supp_table_s2_complete.html"))))
files<-c(list.files(file.path(p,"helpers"),full.names=TRUE),list.files(file.path(p,"project"),recursive=TRUE,full.names=TRUE,all.files=TRUE,no..=TRUE))
files<-files[!file.info(files)$isdir & !grepl("/render_|/[.]quarto/",files)]
stopifnot(all(Sys.readlink(files)==""))
d<-data.frame(path=files,bytes=file.info(files)$size,sha256=vapply(files,sha,character(1)))
write.csv(d,file.path(p,"evidence/round2_inputs.csv"),row.names=FALSE)
write_json(list(status="PASS",changed_from_initial_inputs=changed,changes_exactly_documented=TRUE,S2_accessibility_and_style_id_reversal_exact=TRUE,source_prose_unchanged=TRUE,input_count=nrow(d),scratch="/private/tmp/nh_order009_kgqi5px0"),file.path(p,"evidence/round2_preflight.json"),pretty=TRUE,auto_unbox=TRUE)
cat("PASS: five documented layout/helper changes; all other61-inventory inputs exact; S2 content reversal exact.\n")
