stopifnot(as.character(getRversion()) == "4.6.1")
suppressPackageStartupMessages(library(xml2))
suppressPackageStartupMessages(library(jsonlite))
suppressPackageStartupMessages(library(digest))
root <- normalizePath(getwd())
p <- file.path(root, "audit/manuscript_nature_health/final_review_production_2026_09_14")
sha <- function(f) digest(f, file = TRUE, algo = "sha256")
compact <- function(x) gsub("[[:space:]\u00a0]+", "", x)
visible <- function(n) {
  if (xml_type(n) == "text") return(xml_text(n))
  if (xml_type(n) == "comment") return("")
  style <- xml_attr(n, "style"); cls <- xml_attr(n, "class")
  if ((!is.na(style) && grepl("display:\\s*none|clip-path", style)) || (!is.na(cls) && grepl("sr-only|visually-hidden", cls))) return("")
  if (xml_name(n) == "br") return(" ")
  paste0(vapply(xml_contents(n), visible, character(1)), collapse = "")
}
info <- fromJSON(file.path(p, "editable_tables/round2/table_manifest.json"), simplifyVector = FALSE)
html <- fromJSON(file.path(p, "evidence/html_semantic_pass_round2.json"))
tabs <- xml_find_all(read_html(html$html), "//table[contains(concat(' ',normalize-space(@class),' '),' gt_table ')]")
checks <- list(); details <- list()
check <- function(id, ok, detail = "") checks[[length(checks)+1L]] <<- data.frame(id = id, pass = isTRUE(ok), detail = detail)
check("19_documents", length(info) == 19L && length(tabs) == 19L)
ns <- c(w = "http://schemas.openxmlformats.org/wordprocessingml/2006/main")
for (i in seq_along(info)) {
  rec <- info[[i]]; path <- rec$path; label <- rec$label
  check(paste0(label, "_identity"), sha(path) == rec$sha256)
  doc <- read_xml(unz(path, "word/document.xml"))
  wt <- xml_find_all(doc, "//w:body/w:tbl", ns)
  check(paste0(label, "_one_native_table"), length(wt) == 1L)
  wc <- xml_find_all(wt, "./w:tr/w:tc", ns)
  actual <- compact(vapply(wc, function(c) paste0(xml_text(xml_find_all(c, ".//w:t", ns)), collapse = ""), character(1)))
  sc <- xml_find_all(tabs[[i]], "./thead/tr/*[self::th or self::td]|./tbody/tr/*[self::th or self::td]")
  expected <- compact(vapply(sc, visible, character(1)))
  check(paste0(label, "_ordered_nonempty_cells"), identical(actual[nzchar(actual)], expected[nzchar(expected)]))
  check(paste0(label, "_column_grid"), length(xml_find_all(wt, "./w:tblGrid/w:gridCol", ns)) == rec$columns)
  paragraphs <- xml_find_all(doc, "//w:body/w:p", ns)
  paragraph_text <- compact(vapply(paragraphs, function(n) paste0(xml_text(xml_find_all(n, ".//w:t", ns)), collapse=""), character(1)))
  notes <- compact(vapply(xml_find_all(tabs[[i]], "./tfoot/tr/*[self::th or self::td]"), visible, character(1)))
  check(paste0(label, "_notes_exact"), all(notes[nzchar(notes)] %in% paragraph_text))
  fonts <- xml_attr(xml_find_all(wt, ".//w:rFonts", ns), "w:ascii", ns)
  check(paste0(label, "_arial_native_font"), length(fonts)>0L && all(fonts == "Arial"))
  if (label == "Table_S2") {
    all_text <- paste0(xml_text(xml_find_all(wt, ".//w:t", ns)), collapse = "")
    units <- xml_text(xml_find_all(tabs[[i]], ".//span[@data-whole-mean-sd]"))
    tokens <- gsub(" ", "\u00a0", units, fixed = TRUE)
    check("S2_170_unbroken_mean_SD_units", length(tokens) == 170L && all(vapply(tokens, grepl, logical(1), x=all_text, fixed=TRUE)))
    members <- unzip(path, list = TRUE)
    media <- members[grepl("^word/media/.*[.]png$", members$Name), ]
    hashes <- vapply(seq_len(nrow(media)), function(j) { con <- unz(path, media$Name[j], open="rb"); on.exit(close(con)); digest(readBin(con, "raw", n=media$Length[j]), algo="sha256", serialize=FALSE) }, character(1))
    source_hashes <- vapply(xml_attr(xml_find_all(tabs[[i]], ".//img"), "src"), function(src) digest(base64_dec(sub("^data:image/png;base64,", "", src)), algo="sha256", serialize=FALSE), character(1))
    check("S2_17_exact_embedded_PNGs", nrow(media) == 17L && identical(sort(unname(hashes)),sort(unname(source_hashes))))
    check("S2_native_size_not_reduced", rec$numeric_reduction_pt == 0L && rec$numeric_base_font_pt == 10L)
  }
  details[[i]] <- data.frame(label=label,path=path,sha256=sha(path),nonempty_cells=sum(nzchar(actual)),columns=rec$columns)
}
result <- do.call(rbind, checks)
write.csv(result, file.path(p,"evidence/native_structural_checks_round2.csv"), row.names=FALSE)
write.csv(do.call(rbind,details), file.path(p,"evidence/native_document_identities_round2.csv"), row.names=FALSE)
writeLines(capture.output(sessionInfo()), file.path(p,"evidence/native_R_session_round2.txt"))
rec <- list(status=if(all(result$pass))"PASS" else "FAIL", checks=nrow(result),passed=sum(result$pass),documents=19L,scientific_recalculation=FALSE)
write_json(rec,file.path(p,"evidence/native_structural_result_round2.json"),auto_unbox=TRUE,pretty=TRUE)
print(result[!result$pass,],row.names=FALSE)
cat(sum(result$pass),"/",nrow(result),"native Word content/structure checks passed\n")
stopifnot(all(result$pass))
