options(warn = 2)
stopifnot(getRversion() == "4.6.1")
root <- normalizePath(getwd(), mustWork = TRUE)
out <- "/private/tmp/order72k-s2-recovery.FRG4Vi"
w <- "audit/manuscript_nature_health/revision_2026_09_11/consolidated_display_repair_order72k"
d <- "audit/report_harmonization/report018_order72k_non_s5_integration_dispatch"
full <- function(p) ifelse(startsWith(p, "/"), p, file.path(root, p))
sha <- function(p) digest::digest(file = p, algo = "sha256", serialize = FALSE)
pin <- function(p) {
  f <- full(p)
  stopifnot(file.exists(f), !dir.exists(f), Sys.readlink(f) == "")
  data.frame(path = p, sha256 = sha(f), bytes = unname(file.info(f)$size))
}
checks <- list()
ck <- function(id, x, detail) {
  checks[[length(checks) + 1L]] <<- data.frame(check = id, pass = isTRUE(x), detail = detail)
  if (!isTRUE(x)) stop(id, ": ", detail)
}
orig <- read.csv(full(file.path(w, "stopped_final_checks/original_429_identities.csv")), stringsAsFactors = FALSE)
ck("original_inventory_shape", nrow(orig) == 429L && all(orig$final_exact), "Stored 429-row preservation check")
owner_path <- file.path(w, "stopped_owner_manifest.csv")
ck("owner_manifest_sha", sha(full(owner_path)) == "445ba04dd59cd3ef1be2d1d7bc625c8b4f8ce3852b97d48a9d80f86c3f667d25", "Exact sealed 263-row owner manifest")
owner <- read.csv(full(owner_path), stringsAsFactors = FALSE)
ck("owner_manifest_shape", nrow(owner) == 263L && !anyDuplicated(owner$path) && !owner_path %in% owner$path, "Unique non-circular owner manifest")
owner_obs <- do.call(rbind, lapply(owner$path, pin))
owner_exact <- owner$sha256 == owner_obs$sha256 & owner$bytes == owner_obs$bytes
ck("owner_manifest_members", all(owner_exact), "263/263 owner stopped-state members exact")
write.csv(data.frame(owner[,c("path","sha256","bytes")], observed_sha256 = owner_obs$sha256, observed_bytes = owner_obs$bytes, pass = owner_exact), file.path(out, "owner_manifest_rehash.csv"), row.names = FALSE)
ck("owner_stop_record", sha(full(file.path(w, "stopped_return.md"))) == "7e45b0b3398f9c3d6abcbb8ef6880329a2f48f1390b032ed6ba6e86804dc9d46", "Final stopped return and visual lease release reproduced")
hashes <- vapply(full(orig$path), sha, character(1))
ck("original_inventory_rehash", all(hashes == orig$expected_sha256) && all(file.info(full(orig$path))$size == orig$bytes), "All 429 original authority/input rows remain exact")
write.csv(data.frame(path = orig$path, expected_sha256 = orig$expected_sha256, observed_sha256 = hashes, exact = hashes == orig$expected_sha256), file.path(out, "original_rehash.csv"), row.names = FALSE)
cmd <- jsonlite::fromJSON(full(file.path(w, "capture_s2_attempt2_command.json")))
log <- paste(readLines(full(file.path(w, "capture_s2_attempt2.log")), warn = FALSE), collapse = "\n")
ck("failed_same_runtime", identical(cmd$sandbox_permissions, "use_default") && cmd$result$exit_code == 1 && cmd$chrome_pid == 36917 && endsWith(cmd$command, "capture_s2_attempt2 only-s2"), "Exact only-s2 invocation failed under use_default")
ck("launch_stop", all(vapply(c("browserType.launch", "Target page, context or browser has been closed", "kill EPERM", "SIGABRT", "pid=36917"), function(s) grepl(s, log, fixed = TRUE), logical(1))), "Launch failure and process-exit record, not a reported URL-policy rejection")
ck("no_attempt2_output", !file.exists(full(file.path(w, "capture_s2_attempt2"))), "Failed capture destination does not exist")
ck("no_attempt3_output", !file.exists(full(file.path(w, "capture_s2_attempt3"))), "Final adjustment destination is unused")
h <- full(file.path(w, "helpers/capture_word_tables.mjs"))
ck("unchanged_correction_helper", sha(h) == "8dd21ba1d978e36d1cafa0669b7c2456306b66e996f013f44b86ebc2549e0174", "Current helper equals exact retained S2 correction postimage")
ht <- paste(readLines(h, warn = FALSE), collapse = "\n")
ck("same_browser_and_subset", all(vapply(c('"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"', 'executablePath: chromePath', 'captureSubset !== "only-s2"', 'activeSpecs.filter((s) => !captureSubset || s.key === "supp_table_s2")', 'for (const [key, sourcePath] of [])', 'Capture destination already exists; no implicit retry'), function(s) grepl(s, ht, fixed = TRUE), logical(1))), "Same installed Chrome, only-s2 subset, unique output, figure capture disabled")
served <- jsonlite::fromJSON(full(file.path(w, "server_preflight.json")))
session <- jsonlite::fromJSON(full(file.path(w, "server_session.json")))
ck("old_server_closed", session$status == "closed" && session$host == "127.0.0.1" && session$port == 58005 && session$pid == 35776, "Old lifecycle closed at 2026-09-11T19:32:18Z")
files <- served$files
ck("served_source_copy_exact", all(vapply(files$source, sha, character(1)) == files$sha256) && all(vapply(files$served, sha, character(1)) == files$sha256), paste(nrow(files), "rendered source/copy pairs exact"))
all_paths <- list.files(served$root, recursive = TRUE, all.files = TRUE, no.. = TRUE, include.dirs = TRUE, full.names = TRUE)
ck("served_no_symlinks", all(Sys.readlink(all_paths) == ""), "No symlink under existing minimal preview")
live_files <- all_paths[!dir.exists(all_paths)]
ck("served_exact_set", setequal(live_files, files$served), "No unlisted served file")
table_source <- "audit/manuscript_nature_health/figure_table_selection_assets/tbl-near-eye-metrics.html"
ck("frozen_table_source", sha(full(table_source)) == "6832c791ed3ebcf8895106dafe68c7c5118a12a74e37aacdeb8a84b02d9bfe97", "Accepted S2 table fragment exact")
html <- full(file.path(w, "preview_attempt1/main/ZaunerEtAl2026_NatHealth_phase3_brown.html"))
dom <- xml2::read_html(html)
ep <- xml2::xml_find_all(dom, "//*[@id='tbl-near-eye-metrics']")
ck("unique_s2_endpoint", length(ep) == 1L, "One served S2 endpoint")
tbl <- xml2::xml_find_all(ep, ".//table")
if (xml2::xml_name(ep) == "table") tbl <- ep
rows <- xml2::xml_find_all(tbl, ".//tbody/tr")
widths <- vapply(rows, function(r) length(xml2::xml_find_all(r, "./th|./td")), integer(1))
imgs <- xml2::xml_find_all(tbl, ".//tbody//img")
ck("s2_structural_content", length(tbl) == 1L && length(rows) == 23L && sum(widths == 14L) == 17L && length(imgs) == 17L, "23 body rows including 17 fourteen-column data rows, 17 distribution images")
captures <- file.path(w, "capture_attempt1", list.files(full(file.path(w, "capture_attempt1")), recursive = TRUE, all.files = TRUE, no.. = TRUE))
capture_pins <- do.call(rbind, lapply(captures, pin))
write.csv(capture_pins, file.path(out, "completed_capture_pins.csv"), row.names = FALSE)
ck("reusable_capture_files", all(file.exists(full(file.path(w, "capture_attempt1", c("supp_table_s5_part_01.png", "supp_table_s6_part_01.png", "supp_table_s10_part_01.png", "supp_table_s10_part_02.png"))))), "All completed S5/S6/S10 PNG parts exist")
runtime <- c("/Users/zauner/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/bin/node", "/Users/zauner/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json", "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", "/Applications/Google Chrome.app/Contents/Info.plist")
runtime_pins <- do.call(rbind, lapply(runtime, pin))
write.csv(runtime_pins, file.path(out, "runtime_pins.csv"), row.names = FALSE)
extra <- file.path(w, c("capture_s2_attempt2_command.json", "capture_s2_attempt2.log", "capture_attempt1_command.json", "server_preflight.json", "server_session.json", "helpers/capture_word_tables.mjs", "helpers/serve_preview.py", "correction_preflight/correction_manifest.json", "stopped_final_checks/original_429_identities.csv", "stopped_final_checks/served_output_identities.csv", "stopped_final_checks/unchanged_candidate_qmds.csv", "stopped_final_checks/initial_capture_cell_image_preservation.csv", "stopped_final_checks/lua_copy_identities.csv"))
qmds <- c(file.path(w, "project/ZaunerEtAl2026_NatHealth_phase3_brown.qmd"), file.path(w, "project/supplementary_information_outline.qmd"), "audit/manuscript_nature_health/consolidated_display_repair_2026_09_11/integration_candidate_order72k/project/selection.qmd")
paths <- sort(unique(c(extra, qmds, table_source, captures, files$source, files$served, runtime, owner_path, file.path(w,c("stopped_return.md","trial_ledger.csv")), file.path(d, c("capture_s2_environment_stop.md", "lua_dependency_closure_addendum.md", "lua_dependency_closure_pins.csv")), "audit/report_harmonization/owner_orders/72k_non_s5_svg_and_table_preview_integration.md", "audit/report_harmonization/owner_orders/72k_environment_cache_recovery_001.md")))
pins <- do.call(rbind, lapply(paths, pin))
write.csv(pins, file.path(out, "input_pins.csv"), row.names = FALSE)
write.csv(do.call(rbind, checks), file.path(out, "checks.csv"), row.names = FALSE)
writeLines(c(capture.output(sessionInfo()), paste("digest", packageVersion("digest")), paste("jsonlite", packageVersion("jsonlite")), paste("xml2", packageVersion("xml2"))), file.path(out, "session.txt"))
cat(sprintf("ORDER72K_S2_STOP_AUDIT=PASS checks=%d original=429/429 inputs=%d captures=%d served=%d R=%s browser_runs=0\n", length(checks), nrow(pins), nrow(capture_pins), nrow(files), getRversion()))
print(pins[pins$path %in% c(file.path(w, "helpers/capture_word_tables.mjs"), file.path(w, "capture_s2_attempt2_command.json"), file.path(w, "capture_s2_attempt2.log")), ], row.names = FALSE)
