options(warn = 2)
stopifnot(getRversion() == "4.6.1")
root <- normalizePath(getwd(), mustWork = TRUE)
src <- "/private/tmp/order72k-s2-recovery.FRG4Vi"
rel <- "audit/report_harmonization/report018_order72k_s2_capture_recovery_001"
dest <- file.path(root, rel)
order <- "audit/report_harmonization/owner_orders/72k_s2_capture_environment_recovery_001.md"
full <- function(p) ifelse(startsWith(p, "/"), p, file.path(root, p))
sha <- function(p) digest::digest(file = p, algo = "sha256", serialize = FALSE)
pin <- function(p) {
  f <- full(p)
  stopifnot(file.exists(f), !dir.exists(f), Sys.readlink(f) == "")
  data.frame(path = p, sha256 = sha(f), bytes = unname(file.info(f)$size))
}
files <- c("check_s2_stop.R", "seal_recovery.R", "original_rehash.csv", "owner_manifest_rehash.csv", "completed_capture_pins.csv", "runtime_pins.csv", "input_pins.csv", "checks.csv", "session.txt")
stopifnot(all(file.exists(file.path(src, files))), !any(file.exists(file.path(dest, files))))
stopifnot(all(file.copy(file.path(src, files), file.path(dest, files), overwrite = FALSE, copy.mode = TRUE)))
checks <- read.csv(file.path(dest, "checks.csv"), stringsAsFactors = FALSE)
stopifnot(nrow(checks) == 20L, all(checks$pass))
inputs <- read.csv(file.path(dest, "input_pins.csv"), stringsAsFactors = FALSE)
stopifnot(nrow(inputs) == 72L, !anyDuplicated(inputs$path))
actual <- do.call(rbind, lapply(inputs$path, pin))
stopifnot(all(actual$sha256 == inputs$sha256), all(actual$bytes == inputs$bytes))
paths <- sort(unique(c(order, inputs$path, file.path(rel, c(files, "independent_disposition.md")))))
m <- do.call(rbind, lapply(paths, pin))
mp <- file.path(rel, "release_manifest.csv")
stopifnot(!file.exists(full(mp)), !mp %in% m$path, !anyDuplicated(m$path))
write.csv(m, full(mp), row.names = FALSE)
observed <- do.call(rbind, lapply(m$path, pin))
verification <- data.frame(m, observed_sha256 = observed$sha256, observed_bytes = observed$bytes, pass = m$sha256 == observed$sha256 & m$bytes == observed$bytes)
stopifnot(all(verification$pass))
write.csv(verification, file.path(dest, "release_verification.csv"), row.names = FALSE)
dispatch_paths <- c(order, file.path(rel,c("independent_disposition.md","input_pins.csv","runtime_pins.csv","checks.csv","release_manifest.csv","release_verification.csv")))
dispatch <- do.call(rbind, lapply(dispatch_paths, pin))
dp <- file.path(rel,"dispatch_manifest.csv")
stopifnot(!file.exists(full(dp)), !dp %in% dispatch$path)
write.csv(dispatch, full(dp), row.names = FALSE)
key <- do.call(rbind, lapply(c(order, file.path(rel,c("input_pins.csv","release_manifest.csv","dispatch_manifest.csv"))), pin))
write.csv(key, file.path(dest,"key_identities.csv"), row.names=FALSE)
print(key, row.names=FALSE)
cat(sprintf("ORDER72K_S2_RECOVERY_SEAL=PASS checks=20 owner=263/263 originals=429/429 inputs=72/72 release=%d/%d dispatch=7/7 R=%s browser_runs=0\n",nrow(m),nrow(m),getRversion()))
