suppressPackageStartupMessages({
  library(digest)
  library(xml2)
  library(jsonlite)
})
stopifnot(as.character(getRversion()) == "4.6.1")
project_root <- normalizePath(getwd(), mustWork = TRUE)
central_rel <- "audit/report_harmonization/report018_order72f_standalone_output_recovery"
central <- file.path(project_root, central_rel)
stopifnot(!dir.exists(central))
owner <- "audit/manuscript_nature_health/figure_table_selection_svg_revision_2026_09_11"
qmd <- "audit/manuscript_nature_health/manuscript_figure_table_selection.qmd"
old_html <- "audit/manuscript_nature_health/manuscript_figure_table_selection.html"
sibling <- "audit/manuscript_nature_health/manuscript_figure_table_selection_order72f_candidate.html"
destination <- file.path(owner, "rendered/manuscript_figure_table_selection.html")
probe_root <- "/private/tmp/order72f-standalone-recovery.2RDP7v/probe"
probe_qmd <- file.path(probe_root, "audit/manuscript_nature_health/manuscript_figure_table_selection.qmd")
probe_html <- file.path(probe_root, "audit/manuscript_nature_health/manuscript_figure_table_selection_order72f_candidate.html")
sha <- function(path) digest(path, algo = "sha256", file = TRUE, serialize = FALSE)
bytes <- function(path) as.numeric(file.info(path)$size)
rows <- function(paths) data.frame(path = paths, sha256 = unname(vapply(paths, sha, character(1))), bytes = unname(vapply(paths, bytes, numeric(1))))
checks <- list()
check <- function(id, ok, observed) {
  checks[[length(checks) + 1L]] <<- data.frame(check = id, pass = isTRUE(ok), observed = paste(observed, collapse = ";"))
  if (!isTRUE(ok)) stop(id, ": ", paste(observed, collapse = ";"))
}
check("source_postimage", sha(qmd) == "9acec033d0c24cbb0ee7649c38f55d5cea90052e11b6be7fc5f9e7310890d8f3", c(sha(qmd), bytes(qmd)))
check("canonical_html_unmodified", sha(old_html) == "82100e0d3990dec39f61e94970e7a434b02cf94a6d25819ede1be4d24f4130a6", c(sha(old_html), bytes(old_html)))
check("candidate_locations_absent", !file.exists(sibling) && !file.exists(destination), c(sibling, destination))
rendered_files <- if (dir.exists(file.path(owner, "rendered"))) list.files(file.path(owner, "rendered"), recursive = TRUE, all.files = TRUE, no.. = TRUE) else character()
check("rendered_root_empty", length(rendered_files) == 0L, length(rendered_files))
release <- read.csv("audit/report_harmonization/report018_order72e_selection_svg_preview/release_manifest.csv", stringsAsFactors = FALSE)
check("historical_release_shape", nrow(release) == 63L && !anyDuplicated(release$path), nrow(release))
release_actual <- rows(release$path)
delta <- release$path[release_actual$sha256 != release$sha256 | release_actual$bytes != release$bytes]
check("exact_one_authorized_source_transition", identical(delta, qmd), delta)
source_checks <- read.csv(file.path(owner, "qa/source_checks.csv"), stringsAsFactors = FALSE)
check("stored_source_checks", nrow(source_checks) == 20L && all(source_checks$pass), nrow(source_checks))
check("durable_preimages", sha(file.path(owner, "preimages/manuscript_figure_table_selection.qmd")) == release$sha256[release$path == qmd] && sha(file.path(owner, "preimages/manuscript_figure_table_selection.html")) == sha(old_html), "both exact")
check("source_candidate_equals_promoted_source", sha(file.path(owner, "source_candidate/manuscript_figure_table_selection.qmd")) == sha(qmd), sha(qmd))
expected_probe_qmd <- paste0(paste(c("---", "title: \"Standalone output-path fixture\"", "format:", "  html:", "    theme: cosmo", "    toc: true", "    embed-resources: true", "execute:", "  enabled: false", "---", "", "## Fixture", "", "<img src=\"../../artifacts/fixture.svg\" alt=\"Synthetic blue rectangle labelled fixture.\">", "", "{{< include fragments/table.html >}}"), collapse = "\n"), "\n")
probe_raw <- readBin(probe_qmd, "raw", n = bytes(probe_qmd))
check("fixture_source_unchanged", identical(probe_raw, charToRaw(expected_probe_qmd)), sha(probe_qmd))
check("fixture_correct_output_only", file.exists(probe_html) && !file.exists(file.path(dirname(probe_html), "manuscript_figure_table_selection.html")), basename(probe_html))
doc <- read_html(probe_html)
imgs <- xml_find_all(doc, "//img")
check("fixture_embedded_svg", length(imgs) == 1L && startsWith(xml_attr(imgs, "src"), "data:image/svg+xml;base64,"), length(imgs))
decoded <- base64_dec(sub("data:image/svg+xml;base64,", "", xml_attr(imgs, "src"), fixed = TRUE))
check("fixture_svg_bytes_exact", digest(decoded, algo = "sha256", serialize = FALSE) == sha(file.path(probe_root, "artifacts/fixture.svg")), sha(file.path(probe_root, "artifacts/fixture.svg")))
check("fixture_relative_include", length(xml_find_all(doc, "//table[@id='fixture-table']")) == 1L, "one included table")
actual_probe_files <- sort(list.files(probe_root, recursive = TRUE, all.files = TRUE, no.. = TRUE, full.names = TRUE))
check("fixture_no_support_sidecar", length(actual_probe_files) == 4L && !any(dir.exists(actual_probe_files)), length(actual_probe_files))
check("fixture_symlink_free", all(!nzchar(Sys.readlink(actual_probe_files))), length(actual_probe_files))
cli <- readLines("/Applications/quarto/bin/quarto.js", warn = FALSE)
cli_match <- which(grepl("--output option cannot specify a relative or absolute path", cli, fixed = TRUE))
check("installed_cli_path_restriction", length(cli_match) == 1L, cli_match)
quarto_version <- system2("quarto", "--version", stdout = TRUE)
check("installed_quarto_version", identical(quarto_version, "1.9.37"), quarto_version)
selection_text <- paste(readLines(qmd, warn = FALSE), collapse = "\n")
bt <- intToUtf8(96L)
check("source_nonexecuting", grepl("execute:\n  enabled: false", selection_text, fixed = TRUE) && grepl("embed-resources: true", selection_text, fixed = TRUE) && !grepl(paste0(bt, bt, bt, "\\{|", bt, "r[[:space:]]"), selection_text), "Markdown-only; embedded resources")
owner_files <- sort(list.files(owner, recursive = TRUE, all.files = TRUE, no.. = TRUE, full.names = TRUE))
owner_files <- owner_files[!dir.exists(owner_files)]
check("owner_stop_files_readable", length(owner_files) == 14L && all(!nzchar(Sys.readlink(owner_files))), length(owner_files))
dir.create(central, recursive = TRUE)
fixture_dest <- file.path(central, "fixture")
for (path in actual_probe_files) {
  relative <- substring(path, nchar(probe_root) + 2L)
  target <- file.path(fixture_dest, relative)
  dir.create(dirname(target), recursive = TRUE, showWarnings = FALSE)
  stopifnot(file.copy(path, target, overwrite = FALSE), sha(path) == sha(target))
}
stopifnot(file.copy("/private/tmp/order72f-standalone-recovery.2RDP7v/preflight.R", file.path(central, "check_order72f_preflight.R"), overwrite = FALSE))
write.csv(do.call(rbind, checks), file.path(central, "preflight_checks.csv"), row.names = FALSE)
write.csv(rows(owner_files), file.path(central, "owner_stopped_inventory.csv"), row.names = FALSE)
write.csv(rows(unique(c(release$path, owner_files, "audit/report_harmonization/report018_order72e_selection_svg_preview/release_manifest.csv"))), file.path(central, "current_execution_pins.csv"), row.names = FALSE)
write.csv(data.frame(path = delta, historical_sha256 = release$sha256[match(delta, release$path)], current_sha256 = release_actual$sha256[match(delta, release$path)], classification = "Order72e authorized completed source promotion; frozen through Order72f"), file.path(central, "historical_transition_classification.csv"), row.names = FALSE)
writeLines(cli[seq.int(cli_match - 7L, cli_match + 5L)], file.path(central, "installed_cli_output_option_excerpt.txt"))
write_json(list(R = as.character(getRversion()), packages = list(digest = as.character(packageVersion("digest")), xml2 = as.character(packageVersion("xml2")), jsonlite = as.character(packageVersion("jsonlite"))), quarto = quarto_version, fixture_command = "quarto render manuscript_figure_table_selection.qmd --to html --output manuscript_figure_table_selection_order72f_candidate.html", fixture_cwd = dirname(probe_qmd), fixture_exit = 0L, recorded_at_utc = format(Sys.time(), tz = "UTC", usetz = TRUE), project_target_renders_in_this_check = 0L), file.path(central, "verification_context.json"), pretty = TRUE, auto_unbox = TRUE)
cat("ORDER72F_PREFLIGHT=PASS checks=", length(checks), " historical_release=62/63_exact_plus_one_authorized_source_transition owner_stop=", length(owner_files), " fixture=PASS project_render=0 source=", sha(qmd), " bytes=", bytes(qmd), "\n", sep = "")
