stopifnot(as.character(getRversion()) == "4.6.1")
root <- normalizePath(getwd(), mustWork = TRUE)
coord <- "audit/report_harmonization/final_documents_2026_09_13"
audit_dir <- file.path(coord, "writer_environment_recovery_009a")
production <- "audit/manuscript_nature_health/final_review_production_2026_09_14"
evidence <- file.path(production, "evidence")
stage <- file.path(production, "project/manuscript/R0_NatHealth")
order <- file.path(coord, "writer_candidate_production_environment_009a.md")
out <- file.path(coord, "writer_candidate_production_environment_009a_dispatch_manifest.csv")
stopifnot(!file.exists(out), !file.exists(file.path(audit_dir, "checks.csv")))
sha <- function(p) {
  con <- file(p, "rb")
  on.exit(close(con))
  as.character(openssl::sha256(con))
}
audit_manifest <- function(p, base, count, expected) {
  stopifnot(sha(p) == expected)
  x <- read.csv(p, check.names = FALSE, stringsAsFactors = FALSE)
  stopifnot(nrow(x) == count, !anyDuplicated(x$path))
  paths <- ifelse(startsWith(x$path, "/"), x$path, file.path(base, x$path))
  stopifnot(all(file.exists(paths)), !normalizePath(p) %in% normalizePath(paths))
  stopifnot(all(file.info(paths)$size == x$bytes), all(vapply(paths, sha, "") == x$sha256))
  count
}
dispatch <- file.path(coord, "writer_candidate_production_order_009_dispatch_manifest.csv")
n_dispatch <- audit_manifest(dispatch, root, 45L, "07ceb88e078b9a470b5c8835f955dc52e8129dd1549c4a4b79807f3b4041e899")
owner <- "audit/manuscript_nature_health/table_layout_visual_corrections_2026_09_14"
n_owner <- audit_manifest(file.path(owner, "package_manifest.csv"), owner, 263L, "1b5deb90c0c11cd0e931e6b13c00fedf5551920b9be1e890f86ba878ccfceb3b")
receipt_path <- file.path(evidence, "html_round1_command.json")
log_path <- file.path(evidence, "html_round1.log")
receipt <- jsonlite::read_json(receipt_path, simplifyVector = TRUE)
expected_cmd <- c("/Applications/quarto/bin/quarto", "render", "ZaunerEtAl2026_NatHealth_phase3_brown.qmd", "--to", "html", "--no-execute", "--output-dir", "render_html_round1")
stopifnot(identical(receipt$command, expected_cmd), receipt$exit_code == 1L, receipt$status == "FAIL")
stopifnot(receipt$cwd == normalizePath(stage))
inputs <- unlist(receipt$inputs, use.names = TRUE)
paths <- names(inputs)
stopifnot(length(paths) > 40L, all(file.exists(paths)), !anyDuplicated(paths))
actual <- vapply(paths, sha, "")
preservation <- data.frame(path = paths, bytes = file.info(paths)$size, expected_sha256 = unname(inputs), observed_sha256 = unname(actual), pass = unname(actual == inputs))
stopifnot(all(preservation$pass))
log <- paste(readLines(log_path, warn = FALSE), collapse = "\n")
stopifnot(grepl("unable to open database file", log, fixed = TRUE), grepl("Object.openKv", log, fixed = TRUE), grepl("sassCache", log, fixed = TRUE))
target <- file.path(stage, "render_html_round1/ZaunerEtAl2026_NatHealth_phase3_brown.html")
stopifnot(!file.exists(target))
qmds <- list.files(file.path(production, "project"), pattern = "\\.qmd$", recursive = TRUE, full.names = TRUE)
stopifnot(length(qmds) == 3L)
qmd_text <- vapply(qmds, function(p) paste(readLines(p, warn = FALSE), collapse = "\n"), "")
stopifnot(!any(grepl("(?m)^\\s*`{3,}\\{(r|python|julia)([,[:space:]}])", qmd_text, perl = TRUE)))
stopifnot(!any(grepl("`\\{?(r|python|julia)\\s+", qmd_text, perl = TRUE)))
profile <- paste(readLines(file.path(stage, "_quarto.yml"), warn = FALSE), collapse = "\n")
stopifnot(grepl("type: default", profile, fixed = TRUE), grepl("enabled: false", profile, fixed = TRUE), !grepl("pre-render:|post-render:", profile))
quarto_js <- "/Applications/quarto/bin/quarto.js"
bundle <- readLines(quarto_js, warn = FALSE)
stopifnot(!any(grepl("QUARTO_CACHE_DIR", bundle, fixed = TRUE)))
stopifnot(any(grepl('Deno.env.get("HOME")', bundle, fixed = TRUE)))
stopifnot(any(grepl('const kv = await Deno.openKv(kvFile);', bundle, fixed = TRUE)))
stopifnot(any(grepl('quartoCacheDir("sass")', bundle, fixed = TRUE)))
runtime <- c("/Applications/quarto/bin/quarto", quarto_js, "/Applications/quarto/bin/tools/aarch64/deno", "/Applications/quarto/share/version")
runtime_expected <- c("72632b5b855ffec9db28a098cf62b9b83a80c57174bfa733b2b399a7bdef037f", "6c6abf6ecabde086cfe8a3f12bfcd4270b64f5fff75a30cd1d0b30ecf7295338", "bb6fcdcc873419bf59367800e326ddc2345e509e752041c827e979411fe4eb40", "5a31f565b57cfc812a1df236e9887e0befa27ea00d239971405c9fe8f675e62e")
stopifnot(all(vapply(runtime, sha, "") == runtime_expected))
stopifnot(trimws(readLines(runtime[[4]])) == "1.9.37")
write.csv(preservation, file.path(audit_dir, "failed_command_input_preservation.csv"), row.names = FALSE)
for (p in c(receipt_path, log_path)) {
  dest <- file.path(audit_dir, paste0("preserved_", basename(p)))
  stopifnot(!file.exists(dest), file.copy(p, dest), sha(p) == sha(dest))
}
excerpt <- c("Installed Quarto 1.9.37. Direct implementation excerpts, not modified runtime code.", bundle[36075:36131], bundle[79977:79994], bundle[87609:87626])
writeLines(excerpt, file.path(audit_dir, "installed_cache_path_excerpt.txt"))
checks <- data.frame(check = c("R_version", "dispatch", "owner_package", "failed_command_inputs", "exact_target_and_exit", "sass_openKv_failure", "target_HTML_absent", "three_static_QMDs", "default_project_execution_disabled", "unsupported_cache_override", "normal_cache_route", "installed_runtime"), observed = c("4.6.1", "45/45", "263/263", paste0(length(paths), "/", length(paths)), "exact; exit 1", "confirmed", "absent", "no executable/inline engine cells", "confirmed", "not read by installed bundle", "user Library/Caches/quarto/sass/sass.kv", "4/4 exact; 1.9.37"), pass = TRUE)
write.csv(checks, file.path(audit_dir, "checks.csv"), row.names = FALSE)
writeLines(c(capture.output(sessionInfo()), paste("openssl", packageVersion("openssl")), paste("jsonlite", packageVersion("jsonlite"))), file.path(audit_dir, "session.txt"))
members <- sort(unique(c(order, dispatch, file.path(owner, "package_manifest.csv"), paths, receipt_path, log_path, file.path(evidence, c("runtime.json", "preflight_result.json", "staging_result.json", "source_changes.json")), runtime, list.files(audit_dir, recursive = TRUE, full.names = TRUE))))
stopifnot(all(file.exists(members)), !anyDuplicated(members), !out %in% members)
manifest <- data.frame(path = members, bytes = file.info(members)$size, sha256 = vapply(members, sha, ""))
write.csv(manifest, out, row.names = FALSE)
reread <- read.csv(out, stringsAsFactors = FALSE)
stopifnot(all(vapply(reread$path, sha, "") == reread$sha256), !anyDuplicated(normalizePath(reread$path)))
cat(sprintf("ORDER009A_ENVIRONMENT_PREFLIGHT=PASS checks=%d failed_inputs=%d dispatch=%d owner=263 R=4.6.1\n", nrow(checks), length(paths), nrow(manifest)))
cat("order ", sha(order), "\nmanifest ", sha(out), "\n", sep = "")
