# Independent static source reconciliation in R. No layout engine or capture.
stopifnot(getRversion() == "4.6.1")
options(stringsAsFactors = FALSE)
library(xml2)
library(openssl)
library(jsonlite)
project <- "/Users/zauner/Documents/Arbeit/12-TUM/MeLiDos/WP2.2.5_Data_Analysis/ZaunerEtAl_bioRxiv_2026"
package <- file.path(project, "audit/manuscript_nature_health/final_review_manual_table_sources_2026_09_13")
accepted <- file.path(project, "audit/manuscript_nature_health/brown_final_integration_2026_09_13")
args <- commandArgs(trailingOnly = TRUE)
stopifnot(length(args) == 1, grepl("^attempt_[0-9]{2}$", args[1]))
attempt <- file.path(package, args[1]); out <- file.path(attempt, "verification")
stopifnot(dir.exists(attempt), !file.exists(out))
dir.create(out)
file.copy(file.path(package, "verify_static_pages.R"), file.path(out, "verifier_executed.R"))
sha <- function(p) { con <- file(p, "rb"); on.exit(close(con)); paste0(as.character(sha256(con))) }
raw_sha <- function(x) paste0(as.character(sha256(x)))
checks <- list(); pins <- list(); payloads <- list(); row_log <- list(); summaries <- list()
check <- function(name, value, detail = "") {
  checks[[length(checks) + 1L]] <<- data.frame(check = name, pass = isTRUE(value), detail)
  write.csv(do.call(rbind, checks), file.path(out, "checks.csv"), row.names = FALSE)
  if (!isTRUE(value)) stop(paste(name, detail))
}
pin <- function(p, expected = NULL) {
  actual <- sha(p)
  pins[[length(pins) + 1L]] <<- data.frame(path = p, sha256 = actual)
  if (!is.null(expected)) check(paste("identity", basename(p)), identical(actual, expected), p)
  invisible(actual)
}
map_path <- file.path(accepted, "specifications/seven_missing_source_matched_artifacts.csv")
pin(map_path, "efb61fdf50abf8674b55be1aa1bf8d6e9d21379682cbda87e5745221634e3f69")
map <- read.csv(map_path)
made <- read.csv(file.path(attempt, "page_manifest.csv"))
check("exact_seven_source_map_entries", nrow(made) == 7 && identical(map, made[, names(map)]))
expected_pages <- c("table_2_a.html", "table_2_b.html", "table_s2_part_01.html", "table_s2_part_02.html", "table_s2_part_03.html", "table_s7_part_03.html", "table_s7_part_04.html")
check("exact_seven_page_names", identical(made$page, expected_pages))
for (i in seq_len(nrow(made))) {
  m <- made[i, ]; page_path <- file.path(attempt, m$page)
  pin(m$source, m$source_sha256); pin(page_path, m$page_sha256)
  src <- read_html(m$source); page <- read_html(page_path)
  st <- xml_find_first(src, "//table"); rectangle <- xml_find_first(page, "//*[@id='capture-rectangle']")
  check(paste(m$page, "one table in rectangle"), length(xml_find_all(rectangle, ".//table")) == 1)
  nt <- xml_find_first(rectangle, ".//table")
  check(paste(m$page, "fixed rectangle width"), identical(xml_attr(rectangle, "style"), paste0("width:", m$css_width, "px;min-width:", m$css_width, "px;max-width:", m$css_width, "px;")))
  sr <- xml_find_all(st, "./tbody/tr"); nr <- xml_find_all(nt, "./tbody/tr")
  selected <- seq.int(m$row_start + 1L, m$row_end)
  check(paste(m$page, "row count"), length(nr) == length(selected))
  check(paste(m$page, "exact repeated thead"), identical(as.character(xml_find_first(st, "./thead")), as.character(xml_find_first(nt, "./thead"))))
  check(paste(m$page, "source styles exact"), identical(xml_text(xml_find_all(src, "//style")), xml_text(xml_find_all(rectangle, ".//style"))))
  source_css <- paste(xml_text(xml_find_all(src, "//style")), collapse = "\n")
  source_base <- regmatches(source_css, regexpr("(?s)\\.gt_table\\s*\\{.*?font-size:\\s*[0-9]+px;", source_css, perl = TRUE))
  check(paste(m$page, "source font declaration"), grepl(paste0("font-size: ", m$source_font_px, "px;"), source_base, fixed = TRUE))
  new_css <- xml_text(xml_find_first(page, "//style[@id='manual-page-style']"))
  check(paste(m$page, "no capture font override"), !grepl("(?s)#capture[^{}]*\\{[^}]*font", new_css, perl = TRUE))
  unit_nodes <- xml_find_all(nt, ".//*[@data-manual-whole-unit='true']")
  check(paste(m$page, "whole mean-SD unit count"), length(unit_nodes) == m$expected_whole_units)
  if (m$key == "supp_table_s2") {
    colstyles <- xml_attr(xml_find_all(nt, "./colgroup/col"), "style")
    check(paste(m$page, "exact fourteen column widths"), identical(colstyles, paste0("width:", c(200,60,103,rep(96,9),78,185), "px")))
    check(paste(m$page, "whole-unit descendant nowrap protection"), grepl("[data-manual-whole-unit] * { white-space:nowrap !important;", new_css, fixed = TRUE))
    check(paste(m$page, "no numeric clipping"), grepl("padding-left:4px; padding-right:4px; overflow:visible;", new_css, fixed = TRUE))
    check(paste(m$page, "image width containment without resampling"), grepl("img { max-width:100%; object-fit:contain; }", new_css, fixed = TRUE))
  }
  for (j in seq_along(selected)) {
    # Remove only the new static nowrap marker in this in-memory comparison.
    xml_set_attr(xml_find_all(nr[[j]], ".//*[@data-manual-whole-unit]"), "data-manual-whole-unit", NULL)
    original <- as.character(sr[[selected[j]]]); copied <- as.character(nr[[j]])
    check(paste(m$page, "exact source body row", selected[j] - 1L), identical(original, copied))
    cells <- xml_find_all(nr[[j]], "./th|./td")
    spans <- suppressWarnings(as.integer(xml_attr(cells, "colspan"))); spans[is.na(spans)] <- 1L
    check(paste(m$page, "complete column span", selected[j] - 1L), sum(spans) == m$columns)
    row_log[[length(row_log) + 1L]] <- data.frame(page = m$page, source_row_zero_based = selected[j] - 1L, cell_count = length(cells), effective_columns = sum(spans), source_row_sha256 = raw_sha(charToRaw(original)), copied_row_sha256 = raw_sha(charToRaw(copied)))
    imgs_old <- xml_find_all(sr[[selected[j]]], ".//img"); imgs_new <- xml_find_all(nr[[j]], ".//img")
    check(paste(m$page, "exact image tags", selected[j] - 1L), identical(as.character(imgs_old), as.character(imgs_new)))
    if (length(imgs_old)) for (k in seq_along(imgs_old)) {
      uri <- xml_attr(imgs_old[[k]], "src")
      check(paste(m$page, "PNG-only source image", selected[j] - 1L), startsWith(uri, "data:image/png;base64,"))
      raw <- base64_decode(sub("^data:image/png;base64,", "", uri))
      check(paste(m$page, "PNG signature", selected[j] - 1L), identical(as.integer(raw[1:8]), c(137L,80L,78L,71L,13L,10L,26L,10L)))
      dims <- readBin(raw[17:24], integer(), n = 2, size = 4, endian = "big")
      payloads[[length(payloads) + 1L]] <- data.frame(page = m$page, source_row_zero_based = selected[j] - 1L, png_sha256 = raw_sha(raw), uri_sha256 = raw_sha(charToRaw(uri)), bytes = length(raw), width_px = dims[1], height_px = dims[2], original_display_style = xml_attr(imgs_old[[k]], "style"), unchanged = TRUE)
    }
  }
  old_foot <- xml_find_all(st, "./tfoot"); new_foot <- xml_find_all(nt, "./tfoot")
  check(paste(m$page, "notes exact and on specified part"), if (m$keep_notes) identical(as.character(old_foot), as.character(new_foot)) else length(new_foot) == 0)
  ids <- xml_attr(xml_find_all(page, "//*[@id]"), "id")
  check(paste(m$page, "unique standalone IDs"), !anyDuplicated(ids))
  table_ids <- xml_attr(xml_find_all(nt, ".//*[@id]"), "id")
  refs <- unique(unlist(strsplit(xml_attr(xml_find_all(nt, ".//*[@headers]"), "headers"), "\\s+")))
  check(paste(m$page, "headers resolve inside table"), all(refs %in% table_ids))
  for (tag in c("script", "iframe", "object", "embed", "form", "link", "base", "video", "audio", "source")) check(paste(m$page, "no active/fetched tag", tag), length(xml_find_all(page, paste0("//", tag))) == 0)
  attrs <- unlist(lapply(xml_find_all(page, "//*"), function(x) names(xml_attrs(x))))
  check(paste(m$page, "no event handlers"), !any(grepl("^on", attrs, ignore.case = TRUE)))
  check(paste(m$page, "no CSS network fetch"), !grepl("url\\s*\\(|@import|@font-face", paste(xml_text(xml_find_all(page, "//style")), collapse = "\n"), ignore.case = TRUE))
  srcs <- xml_attr(xml_find_all(page, "//*[@src]"), "src")
  check(paste(m$page, "only inline PNG resources"), all(startsWith(srcs, "data:image/png;base64,")))
  csp <- xml_attr(xml_find_first(page, "//meta[@http-equiv='Content-Security-Policy']"), "content")
  check(paste(m$page, "CSP blocks automatic network"), grepl("default-src 'none'", csp, fixed = TRUE) && grepl("connect-src 'none'", csp, fixed = TRUE))
  check(paste(m$page, "instructions outside capture"), length(xml_find_all(rectangle, ".//*[contains(@class,'manual-instructions') or contains(@class,'manual-provenance')]")) == 0)
  summaries[[length(summaries) + 1L]] <- data.frame(page = m$page, css_width = m$css_width, source_body_rows = length(selected), columns = m$columns, whole_units = m$expected_whole_units, source_font_px = m$source_font_px, image_count = sum(vapply(sr[selected], function(z) length(xml_find_all(z, ".//img")), integer(1))), footer_rows = length(xml_find_all(new_foot, "./tr")), header_references = length(refs), structural_pass = TRUE, visual_pass = "NOT ASSESSED", pixel_height = NA_integer_)
}
check("all_170_mean_SD_units_preserved", sum(made$expected_whole_units) == 170)
images <- do.call(rbind, payloads)
check("all_17_embedded_distribution_payloads_preserved", nrow(images) == 17 && all(images$unchanged))
rows <- do.call(rbind, row_log)
s2 <- rows[grepl("^table_s2_", rows$page), ]
s7 <- rows[grepl("^table_s7_", rows$page), ]
check("S2_source_rows_partition_once", identical(s2$source_row_zero_based, 0:22))
check("S7_tail_source_rows_partition_once", identical(s7$source_row_zero_based, 13:22))
members <- read.csv(file.path(accepted, "package_manifest.csv"))
check("accepted_package_all_84_members_unchanged", nrow(members) == 84 && all(vapply(file.path(accepted, members$path), sha, character(1)) == members$sha256))
pin(file.path(accepted, "package_manifest.csv"), "3dcc090cbb74489c15a9df442a5b82cb629c760a5f8dc58d362bed2e3973b8f5")
pin(file.path(accepted, "package_seal.json"), "05c19a2d396c3954de6332707c1c3b4344b9bcf1c0ed3e83c61837c19056bb0d")
for (name in c("ZaunerEtAl2026_NatHealth_phase3_brown.qmd", "supplementary_information_outline.qmd", "_quarto.yml", "references_merged.bib", "manuscript_displays.css")) check(paste("unchanged live", name), sha(file.path(project, "manuscript/R0_NatHealth", name)) == sha(file.path(accepted, "preimages", name)))
pin(file.path(project, "audit/manuscript_nature_health/revision_2026_09_11/consolidated_display_repair_order72k/Nature_Health_non_S5_preview_attempt1.docx"), "f055f0c0f6225e372ed83ddb6bbe189e64f35d7306e7e54af563687991f6492c")
write.csv(images, file.path(out, "embedded_image_payloads.csv"), row.names = FALSE)
write.csv(rows, file.path(out, "exact_source_rows.csv"), row.names = FALSE)
write.csv(do.call(rbind, summaries), file.path(out, "page_structural_summary.csv"), row.names = FALSE)
write.csv(do.call(rbind, pins), file.path(out, "input_pins.csv"), row.names = FALSE)
capture.output(sessionInfo(), file = file.path(out, "sessionInfo.txt"))
write_json(list(status = "STATIC_SOURCE_PASS_ONLY", passing_checks = length(checks), pages = 7, preserved_S2_whole_units = 170, preserved_S2_PNG_payloads = 17, source_S2_font_px = 16, font_reduction = 0, browser_openings = 0, captures = 0, renders = 0, office_processes = 0, visual_pass = FALSE, explanation = "Content, source and declared geometry only. Computed layout, clipping, overlap, readability and native Word fit remain unverified."), file.path(out, "result.json"), auto_unbox = TRUE, pretty = TRUE)
cat("PASS:", length(checks), "static checks; seven pages; 170 mean-SD units; 17 exact image payloads. Visual QA not performed.\n")
