options(warn = 2)
stopifnot(getRversion() == "4.6.1")
root <- normalizePath(getwd(), mustWork = TRUE)
tmp <- "/private/tmp/order72k-cache-audit.d9eWa4"
rel <- "audit/report_harmonization/report018_order72k_environment_cache_recovery_001"
out <- file.path(root, rel)
order <- "audit/report_harmonization/owner_orders/72k_environment_cache_recovery_001.md"
sha <- function(p) digest::digest(file = p, algo = "sha256", serialize = FALSE)
full <- function(p) ifelse(startsWith(p, "/"), p, file.path(root, p))
row <- function(p) {
  f <- full(p)
  stopifnot(file.exists(f), !dir.exists(f), Sys.readlink(f) == "")
  data.frame(path = p, sha256 = sha(f), bytes = unname(file.info(f)$size))
}
stopifnot(!file.exists(file.path(out, "release_manifest.csv")))
evidence <- c("audit_cache_stop.R", "audit_cache_stop_attempt1.R", "audit_cache_stop_attempt2.R", "audit_attempt1_note.md", "audit_attempt2_note.md", "authority_rehash.csv", "candidate_stop_inventory.csv", "runtime_pins.csv", "environment_input_pins.csv", "audit_checks.csv", "installed_cache_implementation.txt", "normal_cache_observation.csv", "session.txt", "seal_environment_recovery.R")
stopifnot(all(file.exists(file.path(tmp, evidence))), !any(file.exists(file.path(out, evidence))))
stopifnot(all(file.copy(file.path(tmp, evidence), file.path(out, evidence), overwrite = FALSE, copy.mode = TRUE)))
pins <- read.csv(file.path(out, "environment_input_pins.csv"), stringsAsFactors = FALSE)
stopifnot(nrow(pins) == 175L, !anyDuplicated(pins$path))
obs <- do.call(rbind, lapply(pins$path, row))
stopifnot(all(pins$sha256 == obs$sha256), all(pins$bytes == obs$bytes))
checks <- read.csv(file.path(out, "audit_checks.csv"), stringsAsFactors = FALSE)
stopifnot(nrow(checks) == 23L, all(checks$pass))
snapshot_dir <- file.path(out, "stopped_preimages")
stopifnot(dir.create(snapshot_dir))
snapshot_paths <- pins$path[grepl("/selection_html_attempt1(_command\\.json|\\.log)$|/environment_stop\\.md$|/project/\\.quarto/project-cache/", pins$path)]
stopifnot(length(snapshot_paths) == 5L)
snapshot <- list()
for (p in snapshot_paths) {
  name <- paste0(substr(sha(full(p)), 1L, 12L), "_", basename(p))
  target <- file.path(snapshot_dir, name)
  stopifnot(file.copy(full(p), target, overwrite = FALSE, copy.mode = TRUE), identical(sha(full(p)), sha(target)))
  snapshot[[length(snapshot) + 1L]] <- data.frame(original_path = p, preserved_path = file.path(rel, "stopped_preimages", name), sha256 = sha(target), bytes = unname(file.info(target)$size))
}
write.csv(do.call(rbind, snapshot), file.path(out, "stopped_preimage_map.csv"), row.names = FALSE)
local <- file.path(rel, list.files(out, recursive = TRUE, all.files = TRUE, no.. = TRUE))
local <- local[!dir.exists(full(local))]
manifest_paths <- sort(unique(c(order, local, pins$path)))
manifest <- do.call(rbind, lapply(manifest_paths, row))
stopifnot(!anyDuplicated(manifest$path), !file.path(rel, "release_manifest.csv") %in% manifest$path)
write.csv(manifest, file.path(out, "release_manifest.csv"), row.names = FALSE)
again <- read.csv(file.path(out, "release_manifest.csv"), stringsAsFactors = FALSE)
current <- do.call(rbind, lapply(again$path, row))
verification <- data.frame(again, observed_sha256 = current$sha256, observed_bytes = current$bytes, pass = again$sha256 == current$sha256 & again$bytes == current$bytes)
stopifnot(all(verification$pass))
write.csv(verification, file.path(out, "release_verification.csv"), row.names = FALSE)
dispatch_paths <- c(order, file.path(rel, c("independent_disposition.md", "environment_input_pins.csv", "runtime_pins.csv", "audit_checks.csv", "release_manifest.csv", "release_verification.csv")))
dispatch <- do.call(rbind, lapply(dispatch_paths, row))
stopifnot(!anyDuplicated(dispatch$path), !file.path(rel, "dispatch_manifest.csv") %in% dispatch$path)
write.csv(dispatch, file.path(out, "dispatch_manifest.csv"), row.names = FALSE)
identities <- do.call(rbind, lapply(c(order, file.path(rel, c("environment_input_pins.csv", "release_manifest.csv", "release_verification.csv", "dispatch_manifest.csv"))), row))
write.csv(identities, file.path(out, "key_identities.csv"), row.names = FALSE)
print(identities, row.names = FALSE)
cat(sprintf("ORDER72K_ENV_RECOVERY_SEAL=PASS environment=175/175 release=%d/%d dispatch=%d R=%s renders=0\n", nrow(manifest), nrow(manifest), nrow(dispatch), getRversion()))
