options(warn = 2, stringsAsFactors = FALSE)
stopifnot(getRversion() == "4.6.1")
p <- "/private/tmp/final-documents-plan.JvA4OY"
out <- "/private/tmp/final-documents-plan-review.GXL1fx"
hash <- function(x) unname(digest::digest(file = x, algo = "sha256", serialize = FALSE))
checks <- data.frame(check = character(), pass = logical())
check <- function(label, result) { stopifnot(length(result) == 1L, isTRUE(result)); checks[nrow(checks) + 1L, ] <<- list(label, result) }
m <- read.csv(file.path(p, "planning_manifest.csv"))
check("planning_manifest_pin", hash(file.path(p, "planning_manifest.csv")) == "fa3c0fa10e299fb91e26669207322cc3f8308fc80d6f6ab1a6bc37f6ffd27a61")
check("planning_seal_pin", hash(file.path(p, "planning_seal.json")) == "68362ef68c04c420892c70616393e6472ab3d51ba7681634536c24084a763dc7")
check("planning_12_exact_non_circular", nrow(m) == 12L && !anyDuplicated(m$path) && !any(basename(m$path) %in% c("planning_manifest.csv", "planning_seal.json")) && all(vapply(m$path, hash, character(1)) == m$sha256) && all(file.info(m$path)$size == m$bytes))
inputs <- read.csv(file.path(p, "current_inputs_and_outputs.csv"))
check("all_52_current_file_pins", nrow(inputs) == 52L && !anyDuplicated(inputs$path) && all(vapply(inputs$path, hash, character(1)) == inputs$sha256) && all(file.info(inputs$path)$size == inputs$bytes))
c <- read.csv(file.path(p, "corpus_37_current_readiness.csv"))
check("37_unique_sources_and_routes", nrow(c) == 37L && !anyDuplicated(c$source) && !anyDuplicated(c$expected_html))
check("all_live_source_snapshot_pins", all(vapply(c$source, hash, character(1)) == c$live_source_sha256))
check("all_37_accepted_html_pins", all(vapply(c$expected_html, hash, character(1)) == c$html_sha256))
check("exactly_16_source_transitions", sum(c$source_sha256 != c$live_source_sha256) == 16L)
check("33_R_bearing_and_4_static", sum(c$R_chunks > 0L) == 33L && sum(c$R_chunks == 0L) == 4L)
b <- read.csv(file.path(p, "website_893_file_current_check.csv"))
build_paths <- file.path("_build/nathealth", b$path)
check("893_current_build_file_pins", nrow(b) == 893L && !anyDuplicated(b$path) && all(vapply(build_paths, hash, character(1)) == b$sha256) && all(file.info(build_paths)$size == b$bytes))
actual_build <- list.files("_build/nathealth", recursive = TRUE, full.names = FALSE, all.files = TRUE, no.. = TRUE)
check("exact_current_build_membership", setequal(actual_build, b$path))
all_build <- list.files("_build/nathealth", recursive = TRUE, full.names = TRUE, all.files = TRUE, no.. = TRUE, include.dirs = TRUE)
check("zero_build_symlinks", all(Sys.readlink(all_build) == ""))
s <- read.csv(file.path(p, "reusable_svg_manifest.csv"))
check("22_SVG_sources_23_appearances_exact", nrow(s) == 22L && sum(s$appearances) == 23L && all(vapply(s$path, hash, character(1)) == s$sha256))
t <- read.csv(file.path(p, "nineteen_editable_table_manifest.csv"))
check("19_native_DOCX_pins", nrow(t) == 19L && !anyDuplicated(t$label) && all(vapply(t$path, hash, character(1)) == t$sha256))
mapping <- read.csv(file.path(p, "table_source_export_dependencies.csv"))
check("19_complete_table_mappings", nrow(mapping) == 19L && setequal(mapping$label, t$label))
check("19_fragment_whole_file_pins", all(vapply(mapping$canonical_source_fragment, hash, character(1)) == mapping$fragment_whole_file_sha256))
check("corrected_main_html_mappings_exact", all(vapply(mapping$latest_corrected_main_html, hash, character(1)) == mapping$latest_corrected_main_html_sha256))
fragment <- "audit/manuscript_nature_health/figure_table_selection_assets/tbl-near-eye-metrics.html"
doc <- xml2::read_html(fragment)
nowrap <- xml2::xml_find_all(doc, ".//span[contains(@style, 'nowrap')]")
check("170_existing_complete_mean_SD_nowrap_spans", sum(grepl("±", xml2::xml_text(nowrap), fixed = TRUE)) == 170L)
write.csv(checks, file.path(out, "planning_snapshot_checks.csv"), row.names = FALSE)
writeLines(c("Read-only artifact/provenance and structure review. No scientific calculations or author-file mutations; no render, browser, producer, promotion or visual PASS.", capture.output(sessionInfo())), file.path(out, "session.txt"))
cat(sprintf("FINAL_DOCUMENTS_PLANNING_REVIEW=PASS checks=%d/%d manifest=12/12 sources=37/37 transitions=16 html=37/37 build=893/893 tables=19/19\n", nrow(checks), nrow(checks)))
