project:
  type: default
  output-dir: _output
  render:
    - ZaunerEtAl2026_NatHealth_phase3_brown.qmd
    - supplementary_information_standalone.qmd

execute:
  enabled: false

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    number-sections: false
    embed-resources: true
    link-external-newwindow: true
  docx:
    toc: false
    number-sections: false

crossref:
  fig-title: "Figure"
  tbl-title: "Table"
