options(warn = 2)
stopifnot(getRversion() == "4.6.1")
out <- "/private/tmp/order72k-s2-guard-stop.j56ooK"
root <- normalizePath(getwd(), mustWork = TRUE)
w <- "audit/manuscript_nature_health/revision_2026_09_11/consolidated_display_repair_order72k"
e <- file.path(w, "s2_width_repair_001")
full <- function(p) ifelse(startsWith(p, "/"), p, file.path(root, p))
sha <- function(p) digest::digest(file = p, algo = "sha256", serialize = FALSE)
pin <- function(p) {
  f <- full(p)
  stopifnot(file.exists(f), !dir.exists(f), Sys.readlink(f) == "")
  data.frame(path = p, sha256 = sha(f), bytes = unname(file.info(f)$size))
}
checks <- list()
ck <- function(id, ok, detail) {
  checks[[length(checks) + 1L]] <<- data.frame(check = id, pass = isTRUE(ok), detail = detail)
  if (!isTRUE(ok)) stop(id)
}
mp <- file.path(e, "stopped_check_owner_manifest.csv")
ck("owner_manifest_sha", sha(full(mp)) == "75259255f98f19a291471e617a42be6bd304db523450167a1eb2c2b9a90045f9", "Exact 335-member stopped owner manifest")
m <- read.csv(full(mp), stringsAsFactors = FALSE)
ck("owner_manifest_shape", nrow(m) == 335L && !anyDuplicated(normalizePath(full(m$path))) && !full(mp) %in% full(m$path), "Unique and non-circular")
obs <- do.call(rbind, lapply(m$path, pin))
owner <- data.frame(m, observed_sha256 = obs$sha256, observed_bytes = obs$bytes, pass = m$sha256 == obs$sha256 & m$bytes == obs$bytes)
ck("owner_members", all(owner$pass), "335/335 exact")
ck("stop_record", sha(full(file.path(e, "stopped_check_return.md"))) == "ec2e2841de79d52ba8cb19dbeb7b1e3aa72d8b7ef2aa75476f8df00a1ea82a51", "Exact STOPPED_CAPTURE_CHECK")
ck("owner_seal", sha(full(file.path(e, "stopped_check_owner_seal.json"))) == "abae2f7983fb83a02b4abc5d8563dce5413c4b90f0b880306dd160cd73dcf7e2", "Exact owner seal")
ck("teardown_sha", sha(full(file.path(e, "teardown_receipt.json"))) == "e46d1d96d5f753309291222eb8b401ac5da4f3fddd0eafc3900de42a188d717d", "Exact teardown evidence")
t <- read.csv(full(file.path(e, "authorized_transitions.csv")), stringsAsFactors = FALSE)
expected_live <- normalizePath(full(c(file.path(w, "helpers/capture_word_tables.mjs"), file.path(w, "project/order72k_layout.css"), "audit/manuscript_nature_health/consolidated_display_repair_2026_09_11/integration_candidate_order72k/project/order72k_layout.css")))
ck("exact_three_aliases", nrow(t) == 3L && !anyDuplicated(t$live) && setequal(normalizePath(t$live), expected_live), "Only helper and two candidate CSS transitions")
ck("live_and_preimage_hashes", all(vapply(t$live, sha, character(1)) == t$post_sha256) && all(vapply(t$preimage, sha, character(1)) == t$pre_sha256), "All three authorized live postimages and retained preimages exact")
h <- read.csv(full(file.path(e, "stopped_2309_rows.csv")), stringsAsFactors = FALSE)
idx <- match(normalizePath(full(h$path)), normalizePath(t$live))
alias <- !is.na(idx)
resolved <- full(h$path)
resolved[alias] <- t$preimage[idx[alias]]
ck("history_resolution", nrow(h) == 2309L && identical(alias, h$historical_preimage_resolution) && all(normalizePath(resolved) == normalizePath(h$resolved_path)) && all(h$expected_sha256[alias] == t$pre_sha256[idx[alias]]), "No unlisted historical alias")
observed <- vapply(resolved, sha, character(1))
historical <- data.frame(path = h$path, expected_sha256 = h$expected_sha256, expected_bytes = h$expected_bytes, resolved_path = resolved, observed_sha256 = observed, observed_bytes = file.info(resolved)$size)
historical$pass <- historical$expected_sha256 == historical$observed_sha256 & historical$expected_bytes == historical$observed_bytes
ck("history_exact", all(historical$pass), "2309/2309 exact with three preimage aliases")
served <- read.csv(full(file.path(e, "served_preflight.csv")), stringsAsFactors = FALSE)
ck("served_pairs", nrow(served) == 12L && all(vapply(served$source, sha, character(1)) == served$sha256) && all(vapply(served$served, sha, character(1)) == served$sha256), "12 immutable source/serve pairs exact")
for (spec in list(c("completed_captures_after.csv", "19"), c("attempt3_after.csv", "8"))) {
  p <- read.csv(full(file.path(e, spec[1])), stringsAsFactors = FALSE)
  ck(spec[1], nrow(p) == as.integer(spec[2]) && all(vapply(full(p$path), sha, character(1)) == p$sha256) && all(file.info(full(p$path))$size == p$bytes), paste(spec[2], "prior captures exact"))
}
files <- list.files(full(file.path(w, "capture_s2_attempt4")), all.files = TRUE, no.. = TRUE)
ck("partial_capture", identical(files, "supp_table_s2_source.html"), "One source HTML; zero part HTML, PNG or completed capture manifest")
server <- jsonlite::fromJSON(full(file.path(e, "server_session.json")))
seal <- jsonlite::fromJSON(full(file.path(e, "stopped_check_owner_seal.json")))
ck("closed_server_and_lease", server$pid == 40429L && server$status == "closed" && server$ended == "2026-09-11T20:28:53Z" && seal$lease_released == "ORDER72K-VISUAL-LEASE-003", "Recorded exact server close and lease003 release")
ck("no_unconsumed_capture_claim", seal$remaining_S2_trials == 0L && seal$consolidated_correction_renders_consumed == 0L && seal$Word_assembly_consumed == 0L && seal$office_QA_consumed == 0L && !seal$visual_acceptance, "Prior S2 allowance exhausted, downstream allowances untouched")
write.csv(owner, file.path(out, "owner_rehash.csv"), row.names = FALSE)
write.csv(historical, file.path(out, "historical_rehash.csv"), row.names = FALSE)
write.csv(do.call(rbind, checks), file.path(out, "checks.csv"), row.names = FALSE)
write.csv(do.call(rbind, lapply(sort(unique(c(m$path, mp, file.path(e, c("stopped_check_owner_seal.json", "stopped_2309_rows.csv", "authorized_transitions.csv")), t$preimage))), pin)), file.path(out, "input_pins.csv"), row.names = FALSE)
writeLines(c("No browser, server, capture, render or owner file mutation by this audit.", capture.output(sessionInfo()), paste("digest", packageVersion("digest")), paste("jsonlite", packageVersion("jsonlite"))), file.path(out, "session.txt"))
cat(sprintf("ORDER72K_ATTEMPT4_STOP=PASS checks=%d owner=335/335 history=2309/2309 aliases=3 served=12 oldcaptures=19+8 PNGs=0 R=%s\n", length(checks), getRversion()))
