h10_abort <- function(message, ..., call. = FALSE) {
  stop(sprintf(message, ...), call. = call.)
}

h10_metric_registry <- function() {
  tibble::tribble(
    ~metric_order,
    ~metric_id,
    ~analysis_unit,
    ~source_field,
    ~response_family,
    ~response_transform,
    ~effect_scale,
    ~lower_bound,
    ~upper_bound,
    ~audit_upper_threshold,
    1L,
    "interdaily_stability",
    "participant",
    "interdaily_stability",
    "gaussian",
    "logit",
    "odds_ratio",
    0,
    1,
    NA_real_,
    2L,
    "intradaily_variability",
    "participant",
    "intradaily_variability",
    "gaussian",
    "identity",
    "difference",
    0,
    NA_real_,
    NA_real_,
    3L,
    "daily_geometric_mean_medi",
    "participant_day",
    "daily_geometric_mean_medi_lx",
    "gaussian",
    "log10_offset_0.1",
    "ratio",
    0,
    NA_real_,
    NA_real_,
    4L,
    "m10_mean_medi",
    "participant_day",
    "m10_mean_medi_lx",
    "gaussian",
    "log10_offset_0.1",
    "ratio",
    0,
    NA_real_,
    NA_real_,
    5L,
    "l10_mean_medi",
    "participant_day",
    "l10_mean_medi_lx",
    "gaussian",
    "log10_offset_0.1",
    "ratio",
    0,
    NA_real_,
    NA_real_,
    6L,
    "duration_above_1000",
    "participant_day",
    "duration_above_1000_h",
    "tweedie_log",
    "identity",
    "ratio",
    0,
    24,
    NA_real_,
    7L,
    "duration_above_250_wake",
    "participant_day",
    "duration_above_250_wake_h",
    "tweedie_log",
    "identity",
    "ratio",
    0,
    NA_real_,
    NA_real_,
    8L,
    "duration_below_10_pre_sleep",
    "participant_day",
    "duration_below_10_pre_sleep_h",
    "gaussian",
    "identity",
    "difference",
    0,
    24,
    6,
    9L,
    "duration_below_1_sleep_environment",
    "participant_day",
    "duration_below_1_sleep_environment_h",
    "tweedie_log",
    "identity",
    "ratio",
    0,
    NA_real_,
    NA_real_,
    10L,
    "longest_bout_above_250",
    "participant_day",
    "longest_bout_above_250_h",
    "gaussian",
    "log10_offset_0.1",
    "ratio",
    0,
    24,
    NA_real_,
    11L,
    "m10_midpoint",
    "participant_day",
    "m10_midpoint_clock_minute",
    "gaussian",
    "clock_minutes",
    "difference",
    0,
    1440,
    NA_real_,
    12L,
    "l10_midpoint",
    "participant_day",
    "l10_midpoint_clock_minute",
    "gaussian",
    "clock_minutes_after_16",
    "difference",
    -1440,
    1440,
    NA_real_,
    13L,
    "mean_timing_above_250",
    "participant_day",
    "mean_timing_above_250_clock_minute",
    "gaussian",
    "clock_minutes",
    "difference",
    0,
    1440,
    NA_real_,
    14L,
    "first_timing_above_250",
    "participant_day",
    "first_timing_above_250_clock_minute",
    "gaussian",
    "clock_minutes",
    "difference",
    0,
    1440,
    NA_real_,
    15L,
    "last_timing_above_250",
    "participant_day",
    "last_timing_above_250_clock_minute",
    "gaussian",
    "clock_minutes",
    "difference",
    0,
    1440,
    NA_real_,
    16L,
    "dose_time_sensitive_corrected_medi",
    "participant_day",
    "dose_corrected_medi_lx_h",
    "gaussian",
    "log10_offset_0.1",
    "ratio",
    0,
    NA_real_,
    NA_real_,
    17L,
    "mder_mean_of_viable_ratios",
    "participant_day",
    "mder",
    "gaussian",
    "identity",
    "difference",
    0,
    NA_real_,
    NA_real_
  )
}

h10_formula_set <- function(analysis_unit) {
  if (!analysis_unit %in% c("participant", "participant_day")) {
    h10_abort("Unknown H10 analysis unit: %s", analysis_unit)
  }
  random <- if (analysis_unit == "participant_day") {
    " + (1 | site:Id)"
  } else {
    ""
  }
  make <- function(rhs) {
    stats::as.formula(paste0("response ~ ", rhs, random))
  }
  list(
    M0 = make("site"),
    M_age = make("site + age_decade"),
    M_age_site = make("site * age_decade"),
    M_sex = make("site + biological_sex"),
    M_sex_site = make("site * biological_sex")
  )
}

h10_comparison_registry <- function() {
  tibble::tribble(
    ~comparison_order,
    ~comparison_id,
    ~predictor,
    ~comparison_role,
    ~reduced_model,
    ~full_model,
    ~family_near_eye,
    ~family_chest,
    1L,
    "AGE-MAIN",
    "age",
    "main_association",
    "M0",
    "M_age",
    "H10-F1-age-main",
    "H10-C1-age-main",
    2L,
    "SEX-MAIN",
    "biological_sex",
    "main_association",
    "M0",
    "M_sex",
    "H10-F2-sex-main",
    "H10-C2-sex-main",
    3L,
    "AGE-SITE",
    "age",
    "site_heterogeneity",
    "M_age",
    "M_age_site",
    "H10-F3-age-site-interaction",
    "H10-C3-age-site-interaction",
    4L,
    "SEX-SITE",
    "biological_sex",
    "site_heterogeneity",
    "M_sex",
    "M_sex_site",
    "H10-F4-sex-site-interaction",
    "H10-C4-sex-site-interaction"
  ) |>
    dplyr::mutate(
      adjustment_method = "BH",
      planned_n = 17L
    )
}

h10_primary_run_registry <- function() {
  tidyr::crossing(
    data_scenario = c("primary", "gap_timing_unaware"),
    placement = c("glasses", "chest")
  ) |>
    dplyr::mutate(
      sample_scenario = "all_available",
      run_id = paste(
        .data$data_scenario,
        .data$placement,
        .data$sample_scenario,
        sep = "__"
      ),
      analytical_role = dplyr::case_when(
        .data$data_scenario == "primary" &
          .data$placement == "glasses" ~
          "primary_near_eye",
        .data$data_scenario == "primary" ~ "complementary_chest",
        .data$placement == "glasses" ~ "gap_timing_unaware_near_eye",
        TRUE ~ "gap_timing_unaware_chest"
      )
    )
}
