stopifnot(as.character(getRversion()) == "4.6.1")
project_root <- normalizePath(getwd(), mustWork = TRUE)
coord <- "audit/report_harmonization/final_documents_2026_09_13"
evidence <- file.path(coord, "candidate_format_recovery_010")
owner <- "audit/hypotheses/H09/manuscript_s15b_strip_layout_2026_09_14"
p <- "audit/manuscript_nature_health/final_review_production_2026_09_14"
old <- "audit/hypotheses/H09/report018_order72j_split_svg_export"
dispatch <- file.path(coord, "h09_s15b_strip_candidate_order_010a_dispatch_manifest.csv")
stopifnot(!dir.exists(owner), !dir.exists(evidence), !file.exists(dispatch))
sha <- function(path) {
  con <- file(path, "rb")
  on.exit(close(con))
  as.character(openssl::sha256(con))
}
writer_manifest <- file.path(p, "candidate_package_manifest.csv")
stopifnot(sha(writer_manifest) == "624753fabeb69a47cc9fe7262cba25849963e8ab8aca201512f47fbb5ec65b32")
m <- read.csv(writer_manifest, stringsAsFactors = FALSE)
stopifnot(nrow(m) == 439L, !anyDuplicated(m$path))
writer_paths <- file.path(p, m$path)
stopifnot(all(file.exists(writer_paths)), !normalizePath(writer_manifest) %in% normalizePath(writer_paths))
m$observed_bytes <- file.info(writer_paths)$size
m$observed_sha256 <- vapply(writer_paths, sha, "")
m$pass <- m$observed_bytes == m$bytes & m$observed_sha256 == m$sha256
stopifnot(all(m$pass))
svg <- file.path(old, "candidate/H09_observed_timing_patterns.svg")
primary <- file.path(old, "candidate/H09_primary_effects.svg")
csv <- "artifacts/11_source_data/H09/H09_observed_timing_patterns_data.csv"
stopifnot(sha(svg) == "c937252509c5de9448944358a9846842c973bac26b0f0fb4640728fcf8a908b3")
stopifnot(sha(primary) == "a3f9bdb969c075d33adf9a0e6e751a1f967d5111856fcd0db07cbc36575a745a")
stopifnot(sha(csv) == "34640aba210181b973902e00cd6924f79f6ae76faf01fa3c5b66078e2e2e7cee")
raw <- readBin(svg, "raw", n = file.info(svg)$size)
txt <- rawToChar(raw)
change <- data.frame(old_x = c("105.65", "324.73", "543.80"), new_x = c("89.13", "308.21", "527.28"))
change$old_prefix <- paste0("<rect x='", change$old_x, "' y='86.06' width='158.96' height='47.66'")
change$new_prefix <- paste0("<rect x='", change$new_x, "' y='86.06' width='192.00' height='47.66'")
count_fixed <- function(pattern, subject) {
  matches <- gregexpr(pattern, subject, fixed = TRUE)[[1]]
  if (identical(matches[[1]], -1L)) 0L else length(matches)
}
change$matches <- vapply(change$old_prefix, count_fixed, 1L, subject = txt)
stopifnot(all(change$matches == 2L))
prospective <- txt
for (i in seq_len(nrow(change))) prospective <- gsub(change$old_prefix[[i]], change$new_prefix[[i]], prospective, fixed = TRUE)
reverse <- prospective
for (i in seq_len(nrow(change))) reverse <- gsub(change$new_prefix[[i]], change$old_prefix[[i]], reverse, fixed = TRUE)
stopifnot(identical(charToRaw(reverse), raw))
order <- file.path(coord, "h09_s15b_strip_candidate_order_010a.md")
disposition <- file.path(coord, "writer009_independent_layout_disposition_010.md")
stopifnot(!any(grepl("\u2014", readLines(order, warn = FALSE), fixed = TRUE)))
stopifnot(!any(grepl("\u2014", readLines(disposition, warn = FALSE), fixed = TRUE)))
dir.create(evidence, recursive = FALSE)
write.csv(m, file.path(evidence, "writer009_439_member_audit.csv"), row.names = FALSE, na = "")
write.csv(change, file.path(evidence, "h09_s15b_exact_rectangle_preflight.csv"), row.names = FALSE)
tmp <- "/private/tmp/writer009-review.tQ1OFF"
copies <- c("inspect.R", "observations.md", "table_source_and_HTML_preservation.csv", "reviewed_input_pins.csv", "S3_owner_route.csv", "session.txt", "audit_final.R", "H09_S15B_strip_geometry.csv", "audit_final_session.txt")
stopifnot(all(file.exists(file.path(tmp, copies))))
stopifnot(all(file.copy(file.path(tmp, copies), file.path(evidence, copies), overwrite = FALSE)))
writeLines(c("Copied from the coordinator's read-only temporary review at /private/tmp/writer009-review.tQ1OFF.", "No owner source or production file was changed. Prospective SVG substitution was tested in memory only; no candidate was generated by the coordinator."), file.path(evidence, "review_provenance.txt"))
checks <- data.frame(check = c("R_version", "writer_manifest", "H09_inputs", "selected_rectangles", "in_memory_reverse", "new_owner_root", "S2_size_accepted", "no_candidate_generated"),
  result = c("4.6.1", "439/439", "3/3", "6/6", "byte-exact", "absent", "preserved", "true"), pass = TRUE)
write.csv(checks, file.path(evidence, "h09_order010a_preflight.csv"), row.names = FALSE)
writeLines(c(capture.output(sessionInfo()), paste("openssl", packageVersion("openssl"))), file.path(evidence, "h09_order010a_session.txt"))
paths <- sort(unique(c(order, disposition, file.path(coord, "seal_h09_s15b_strip_order_010a.R"), writer_manifest,
  file.path(p, c("candidate_production_review.md", "candidate_package_seal.json", "evidence/visual_adjudication_round2.md", "evidence/main_round2_full_page_review.json", "evidence/svg_browser_adjudication/teardown.json", "deliverables/Nature_Health_manuscript_round2.docx", "project/manuscript/R0_NatHealth/render_html_round2/ZaunerEtAl2026_NatHealth_phase3_brown.html")),
  svg, primary, csv, file.path(old, c("code/build_h09_order72j_svg_exports.R", "code/check_h09_order72j_svg_exports.R", "non_circular_manifest.csv", "REPORT018-ORDER72J-COMPONENT-REVIEW.md")),
  list.files(evidence, full.names = TRUE, recursive = TRUE))))
stopifnot(all(file.exists(paths)), !any(file.info(paths)$isdir), !dispatch %in% paths, !anyDuplicated(normalizePath(paths)))
manifest <- data.frame(path = paths, bytes = file.info(paths)$size, sha256 = vapply(paths, sha, ""))
write.csv(manifest, dispatch, row.names = FALSE, na = "")
re <- read.csv(dispatch, stringsAsFactors = FALSE)
stopifnot(nrow(re) == length(paths), !anyDuplicated(re$path), all(file.info(re$path)$size == re$bytes), all(vapply(re$path, sha, "") == re$sha256))
writeLines(paste(vapply(c(order, disposition, dispatch), sha, ""), c(order, disposition, dispatch), sep = "  "), file.path(coord, "h09_s15b_strip_candidate_order_010a.sha256"))
cat(sprintf("H09_S15B_ORDER010A=SEALED writer=439/439 checks=8/8 dispatch=%d/%d\n", nrow(re), nrow(re)))
cat("order ", sha(order), "\ndispatch ", sha(dispatch), "\ndisposition ", sha(disposition), "\n", sep = "")
