shared <- "/Users/zauner/Documents/Arbeit/12-TUM/MeLiDos/WP2.2.5_Data_Analysis/ZaunerEtAl_bioRxiv_2026"
brown <- "/Users/zauner/.codex/worktrees/82ab/ZaunerEtAl_bioRxiv_2026"
out <- file.path(shared, "audit/decisions/brown_main_linkage_b_stage1_release")
stopifnot(as.character(getRversion()) == "4.6.1")
sha <- function(p) unname(digest::digest(file = p, algo = "sha256"))
inv <- function(paths) data.frame(path = paths, bytes = as.numeric(file.info(paths)$size), sha256 = unname(vapply(paths, sha, character(1))), stringsAsFactors = FALSE)
verify <- function(x) {
  stopifnot(!anyDuplicated(x$path), all(file.exists(x$path)))
  y <- inv(x$path)
  stopifnot(identical(y$sha256, x$sha256), identical(y$bytes, as.numeric(x$bytes)))
}
pres <- read.csv(file.path(out, "owner_preservation_pins.csv"), stringsAsFactors = FALSE)
verify(pres)
coord <- read.csv(file.path(out, "coordination_preservation.csv"), stringsAsFactors = FALSE)
verify(coord)
copies <- read.csv(file.path(out, "historical_evidence_copy_inventory.csv"), stringsAsFactors = FALSE)
stopifnot(identical(unname(vapply(copies$preserved_path, sha, character(1))), copies$sha256))
ledger_names <- c("decision_register.csv", "change_log.csv")
ids <- c("BA-017", "CHG-156")
id_fields <- c("decision_id", "change_id")
append_proof <- do.call(rbind, lapply(seq_along(ledger_names), function(i) {
  old_path <- file.path(out, "baseline", ledger_names[i])
  new_path <- file.path(shared, "audit/ledgers", ledger_names[i])
  old_raw <- readBin(old_path, "raw", n = file.info(old_path)$size)
  new_raw <- readBin(new_path, "raw", n = file.info(new_path)$size)
  stopifnot(length(new_raw) > length(old_raw), identical(new_raw[seq_along(old_raw)], old_raw))
  old <- read.csv(old_path, check.names = FALSE, stringsAsFactors = FALSE)
  new <- read.csv(new_path, check.names = FALSE, stringsAsFactors = FALSE)
  stopifnot(nrow(new) == nrow(old) + 1L, identical(new[seq_len(nrow(old)), ], old), !anyDuplicated(new[[id_fields[i]]]), sum(new[[id_fields[i]]] == ids[i]) == 1L, tail(new[[id_fields[i]]], 1) == ids[i])
  data.frame(path = new_path, old_sha256 = sha(old_path), new_sha256 = sha(new_path), old_rows = nrow(old), new_rows = nrow(new), added_identity = ids[i], old_bytes_exact_prefix = TRUE, all_old_rows_exact = TRUE, unique = TRUE)
}))
decision_path <- file.path(shared, "audit/decisions/brown_adherence_main_linkage_b_stage1_reopening.md")
decision <- paste(readLines(decision_path, warn = FALSE), collapse = "\n")
stopifnot(grepl("Status: authorized Stage 1 specification", decision, fixed = TRUE), grepl("not a second FDR family", decision, fixed = TRUE), grepl("Do not execute either completed audit script again", decision, fixed = TRUE), grepl("BA-LB-G1-REVIEW", decision, fixed = TRUE), grepl("BA-LB-G2-REVIEW", decision, fixed = TRUE))
stopifnot(!dir.exists(file.path(brown, "audit/analyses/brown_adherence/main_linkage_b_amendment/stage1")))
write.csv(append_proof, file.path(out, "ledger_append_verification.csv"), row.names = FALSE)
checks <- data.frame(check_id = c("frozen_authority_inputs", "current_owner_preservation", "durable_historical_copies", "ledger_exact_append", "unique_decision_change", "stage1_root_absent", "completed_audit_not_repeated", "ba_m6_sample_specific_family", "mandatory_coordinator_gate", "mandatory_future_author_gate", "hypothesis_matrix_unchanged", "website_manifest_unchanged"), passed = TRUE, detail = c("14/14", paste0(nrow(pres), "/", nrow(pres)), paste0(nrow(copies), "/", nrow(copies)), "2/2 byte prefixes and old rows", "BA-017 and CHG-156 exactly once", "new owner root only", "hash verification and copied evidence only", "one primary family; support-80 stability without second FDR family", "BA-LB-G1-REVIEW", "BA-LB-G2-REVIEW", "exact coordination preservation pin", "exact coordination preservation pin"), stringsAsFactors = FALSE)
write.csv(checks, file.path(out, "release_checks.csv"), row.names = FALSE)
stopifnot(file.copy("/private/tmp/ba017-dispatch.7VdBDq/seal_release.R", file.path(out, "seal_release.R"), overwrite = FALSE))
manifest_path <- file.path(out, "release_manifest.csv")
stopifnot(!file.exists(manifest_path))
evidence <- list.files(out, recursive = TRUE, full.names = TRUE, all.files = TRUE)
stopifnot(all(!file.info(evidence)$isdir))
all_paths <- sort(unique(c(evidence, decision_path, file.path(shared, "audit/ledgers", ledger_names), pres$path)))
stopifnot(!manifest_path %in% all_paths)
manifest <- inv(all_paths)
write.csv(manifest, manifest_path, row.names = FALSE)
verify(read.csv(manifest_path, stringsAsFactors = FALSE))
verify(pres)
verify(coord)
cat("BA017_RELEASE=PASS checks=", nrow(checks), "/", nrow(checks), " manifest=", nrow(manifest), "/", nrow(manifest), " preservation=", nrow(pres), "/", nrow(pres), " ledgers=append_only stage1_root_absent=TRUE\n", sep = "")
print(inv(c(decision_path, file.path(shared, "audit/ledgers", ledger_names), manifest_path, file.path(out, "release_disposition.md"))), row.names = FALSE)
