options(stringsAsFactors = FALSE)
stopifnot(getRversion() == "4.6.1")
root <- normalizePath(getwd(), mustWork = TRUE)
d <- file.path(root, "audit/report_harmonization/report018_order72k_non_s5_integration_dispatch")
record <- file.path(root, "audit/manuscript_nature_health/revision_2026_09_11/consolidated_display_repair_order72k/s2_accessibility_guard_recovery_001")
sha <- function(p) { con <- file(p,"rb"); on.exit(close(con)); as.character(openssl::sha256(con)) }
p <- read.csv(file.path(record,"stopped_owner_manifest.csv"))
paths <- ifelse(startsWith(p$path,"/"),p$path,file.path(root,p$path))
stopifnot(nrow(p)==444L, all(vapply(paths,sha,character(1))==p$sha256), all(file.info(paths)$size==p$bytes))
render <- read.csv(file.path(record,"stopped_correction_render_output_pins.csv"))
stopifnot(all(vapply(render$path,sha,character(1))==render$sha256))
post <- file.path(d,"svg_stop_independent_verified_001/post_browser_rejection_rehash.txt")
stopifnot(!file.exists(post))
writeLines(c("All444 sealed current members remain exact after the single rejected browser entry.","Allthree corrected HTML/HTML/DOCX hashes remain exact. No file, image, helper, assembly or rendering change.","No browser handle was returned; no server or native app was started by this reviewer.","Harmonizer lease005 released. Corrected HTML visual QA is pending manual-author evidence; native Word remains pending unlock.",format(Sys.time(),tz="UTC",usetz=TRUE)),post)
files <- c(file.path(d,c("review_svg_compatibility_stop.R","review_svg_compatibility_stop_verified.R","seal_svg_compatibility_stop.R","visual_lease_004_closed_005_handover.md")),list.files(file.path(d,"svg_stop_independent_001"),full.names=TRUE),list.files(file.path(d,"svg_stop_independent_verified_001"),full.names=TRUE))
stopifnot(!anyDuplicated(files),all(file.exists(files)),all(Sys.readlink(files)==""))
files <- sort(files)
manifest <- file.path(d,"svg_compatibility_stop_independent_manifest.csv")
seal <- file.path(d,"svg_compatibility_stop_independent_seal.json")
stopifnot(!file.exists(manifest),!file.exists(seal))
rows <- data.frame(path=substring(files,nchar(root)+2L),sha256=vapply(files,sha,character(1)),bytes=file.info(files)$size)
write.csv(rows,manifest,row.names=FALSE)
jsonlite::write_json(list(status="STOPPED_DOCX_SVG_PRECONDITION_AND_BROWSER_URL_POLICY",manifest=substring(manifest,nchar(root)+2L),members=nrow(rows),sha256=sha(manifest),writer_manifest_sha256=sha(file.path(record,"stopped_owner_manifest.csv")),visual_lease005="released",assembly_embedding=0L,office_QA=0L,additional_renders=0L),seal,pretty=TRUE,auto_unbox=TRUE)
cat("Independent seal:",nrow(rows),"members",sha(manifest),"\nCompanion:",sha(seal),"\n")
