project:
  type: default
  render: [ZaunerEtAl2026_NatHealth_phase3_brown.qmd]
execute:
  enabled: false
format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    number-sections: false
    embed-resources: true
    link-external-newwindow: true
  docx:
    toc: false
    number-sections: false
    reference-doc: resources/8c0cf634a495_reference.docx
    filters: [resources/d0b0874a22eb_authors-block.lua]
crossref:
  fig-title: "Figure"
  tbl-title: "Table"
