stopifnot(getRversion() == numeric_version("4.6.1"))
shared_root <- "/Users/zauner/Documents/Arbeit/12-TUM/MeLiDos/WP2.2.5_Data_Analysis/ZaunerEtAl_bioRxiv_2026"
brown_root <- "/Users/zauner/.codex/worktrees/82ab/ZaunerEtAl_bioRxiv_2026"
output_root <- "/private/tmp/brown-ba018-release.0VjISc"
release_root <- file.path(shared_root, "audit/decisions/brown_main_linkage_b_stage2_release")
stage1_root <- file.path(brown_root, "audit/analyses/brown_adherence/main_linkage_b_amendment/stage1")
amendment_root <- dirname(stage1_root)
sha <- function(p) unname(digest::digest(file = p, algo = "sha256", serialize = FALSE))
full_paths <- function(p) ifelse(startsWith(p, "/"), p, file.path(shared_root, p))
audit_rows <- function(m, count = NULL) {
  if (!is.null(count)) stopifnot(nrow(m) == count)
  stopifnot(!anyDuplicated(m$path))
  paths <- full_paths(m$path)
  stopifnot(all(file.exists(paths)), !any(file.info(paths)$isdir))
  m$observed_sha256 <- vapply(paths, sha, "")
  m$observed_bytes <- as.numeric(file.info(paths)$size)
  m$pass <- m$sha256 == m$observed_sha256 & as.numeric(m$bytes) == m$observed_bytes
  m
}
input_rows <- read.csv(file.path(release_root, "execution_input_pins.csv"), stringsAsFactors = FALSE)
input_audit <- audit_rows(input_rows, 2174L)
write.csv(input_audit, file.path(output_root, "execution_input_rehash.csv"), row.names = FALSE)
stopifnot(all(input_audit$pass))
stage1_manifest <- file.path(stage1_root, "final_manifest.csv")
stopifnot(sha(stage1_manifest) == "7290ad5f2e595949cde38dcd241bc5f4cb0037094c1a0ed99e03c3252e877dc0")
stage1 <- audit_rows(read.csv(stage1_manifest, stringsAsFactors = FALSE), 89L)
stopifnot(all(stage1$pass), !stage1_manifest %in% full_paths(stage1$path))
write.csv(stage1, file.path(output_root, "stage1_member_rehash.csv"), row.names = FALSE)
protected <- audit_rows(read.csv(file.path(stage1_root, "preexisting_protected_files.csv"), stringsAsFactors = FALSE), 2066L)
stopifnot(all(protected$pass))
write.csv(protected, file.path(output_root, "historical_protected_rehash.csv"), row.names = FALSE)
baseline_pins <- read.csv(file.path(release_root, "pre_append_ledger_pins.csv"), stringsAsFactors = FALSE)
stopifnot(nrow(baseline_pins) == 2L)
ledger_audit <- do.call(rbind, lapply(seq_len(nrow(baseline_pins)), function(i) {
  current <- file.path(shared_root, baseline_pins$path[[i]])
  baseline <- file.path(release_root, "baseline", basename(current))
  stopifnot(sha(baseline) == baseline_pins$sha256[[i]], file.info(baseline)$size == baseline_pins$bytes[[i]])
  before <- readBin(baseline, "raw", n = file.info(baseline)$size)
  after <- readBin(current, "raw", n = file.info(current)$size)
  stopifnot(length(after) > length(before), identical(after[seq_along(before)], before))
  pre <- read.csv(baseline, colClasses = "character", check.names = FALSE, stringsAsFactors = FALSE)
  post <- read.csv(current, colClasses = "character", check.names = FALSE, stringsAsFactors = FALSE)
  stopifnot(identical(names(pre), names(post)), nrow(post) == nrow(pre) + 1L)
  stopifnot(identical(post[seq_len(nrow(pre)), , drop = FALSE], pre))
  id <- if (basename(current) == "decision_register.csv") "BA-018" else "CHG-157"
  stopifnot(sum(post[[1]] == id) == 1L, post[[1]][[nrow(post)]] == id)
  data.frame(path = baseline_pins$path[[i]], baseline_sha256 = sha(baseline), baseline_bytes = length(before), current_sha256 = sha(current), current_bytes = length(after), baseline_rows = nrow(pre), current_rows = nrow(post), appended_id = id, prior_raw_prefix_exact = TRUE, prior_parsed_rows_exact = TRUE, unique_authority_id = TRUE)
}))
write.csv(ledger_audit, file.path(output_root, "ledger_append_verification.csv"), row.names = FALSE)
stopifnot(!dir.exists(file.path(amendment_root, "stage2")), !dir.exists(file.path(amendment_root, "stage3")), !dir.exists(file.path(amendment_root, "stage4")))
stopifnot(!file.exists(file.path(release_root, "release_manifest.csv")), !file.exists(file.path(release_root, "dispatch_message.md")), !file.exists(file.path(release_root, "dispatch_receipt.md")))
gates <- read.csv(file.path(release_root, "independent_replay/gate_replay/finalization_checks.csv"), stringsAsFactors = FALSE)
supports <- read.csv(file.path(release_root, "independent_replay/support_replay/planning_dependency_checks.csv"), stringsAsFactors = FALSE)
gate_comp <- read.csv(file.path(release_root, "independent_replay/gate_replay_comparison.csv"), stringsAsFactors = FALSE)
support_comp <- read.csv(file.path(release_root, "independent_replay/support_replay_comparison.csv"), stringsAsFactors = FALSE)
stopifnot(nrow(gates) == 36L, nrow(supports) == 14L)
cat("REPLAY_COLUMNS\n")
print(lapply(list(gates = gates, supports = supports, gate_comparison = gate_comp, support_comparison = support_comp), names))
cat("LEDGER_APPEND=PASS exact_prefix_and_prior_rows=2/2 one_unique_BA018_CHG157_append\n")
cat("BA018_RELEASE_INPUTS=PASS execution=2174/2174 stage1=89/89 protected=2066/2066 stage2_stage3_stage4_absent no_dispatch_yet\n")
print(ledger_audit)
controls <- c(file.path(shared_root, "audit/decisions/brown_adherence_main_linkage_b_stage2_transition.md"), file.path(release_root, "independent_stage1_acceptance.md"), file.path(release_root, "execution_input_pins.csv"))
write.csv(data.frame(path = controls, sha256 = vapply(controls, sha, ""), bytes = as.numeric(file.info(controls)$size)), file.path(output_root, "control_identities.csv"), row.names = FALSE)
writeLines(c("Read-only release/ledger rehash. No model, data calculation, fit, report or owner write.", paste("digest", packageVersion("digest")), capture.output(sessionInfo())), file.path(output_root, "session_and_scope.txt"))
