stopifnot(as.character(getRversion()) == "4.6.1")
suppressPackageStartupMessages({library(xml2);library(jsonlite);library(digest)})
root <- normalizePath(getwd())
n <- file.path(root,"audit/manuscript_nature_health/final_pagination_completion_2026_09_14")
c <- file.path(root,"audit/manuscript_nature_health/final_format_completion_2026_09_14")
old <- file.path(c,"deliverables/Nature_Health_manuscript_round2.docx")
new <- file.path(n,"deliverables/Nature_Health_manuscript.docx")
sha <- function(p) digest(p,file=TRUE,algo="sha256")
rawsha <- function(x) digest(x,serialize=FALSE,algo="sha256")
members <- function(f) {
  m <- unzip(f,list=TRUE)
  payloads <- lapply(seq_len(nrow(m)),function(i){z<-unz(f,m$Name[i],"rb");on.exit(close(z));readBin(z,"raw",n=m$Length[i])})
  setNames(payloads,m$Name)
}
a<-members(old);b<-members(new);checks<-list()
check<-function(id,pass)checks[[length(checks)+1L]]<<-data.frame(id=id,pass=isTRUE(pass))
check("ZIP_names_and_order",identical(names(a),names(b)))
different<-names(a)[!vapply(names(a),function(k)identical(a[[k]],b[[k]]),logical(1))]
check("sole_document_xml_change",identical(different,"word/document.xml"))
check("exact_XML_postimage",length(b[["word/document.xml"]])==358283L&&rawsha(b[["word/document.xml"]])=="98e2924ccc67952165ada5b01d1904b40eacea517908480b47faf0a0e58ffb7f")
bp<-readBin(file.path(n,"evidence/selected_paragraph_before.xml"),"raw",n=272)
ap<-readBin(file.path(n,"evidence/selected_paragraph_after.xml"),"raw",n=252)
check("selected_paragraph_preimage",rawsha(bp)=="836b1402a77c1d81fbd0fbdd06992a3f05398a12fc6ab9d110f67035bb295ec8")
check("selected_paragraph_postimage",rawsha(ap)=="046cac3f3089d05dd76487e1e415e5f088d9ea88aa6df856ca3392ea8492c311")
reversed<-charToRaw(sub(rawToChar(ap),rawToChar(bp),rawToChar(b[["word/document.xml"]]),fixed=TRUE))
check("exact_reverse_XML",identical(reversed,a[["word/document.xml"]]))
d<-read_xml(b[["word/document.xml"]]);o<-read_xml(a[["word/document.xml"]])
ns<-c(w="http://schemas.openxmlformats.org/wordprocessingml/2006/main",wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing")
check("all_visible_runs_exact",identical(xml_text(xml_find_all(d,"//w:t",ns)),xml_text(xml_find_all(o,"//w:t",ns))))
check("all_54_drawings_exact",length(xml_find_all(d,"//wp:inline",ns))==54L&&identical(as.character(xml_find_all(d,"//wp:inline",ns)),as.character(xml_find_all(o,"//wp:inline",ns))))
check("all_sections_exact",identical(as.character(xml_find_all(d,"//w:sectPr",ns)),as.character(xml_find_all(o,"//w:sectPr",ns))))
check("all_bookmarks_exact",identical(as.character(xml_find_all(d,"//w:bookmarkStart|//w:bookmarkEnd",ns)),as.character(xml_find_all(o,"//w:bookmarkStart|//w:bookmarkEnd",ns))))
p<-xml_find_all(d,"//w:body/w:p",ns);styles<-xml_attr(xml_find_first(p,"./w:pPr/w:pStyle",ns),"val")
txt<-vapply(p,function(x)paste0(xml_text(xml_find_all(x,".//w:t",ns)),collapse=""),character(1))
k<-which(txt=="Supplementary Figure S9. Paired sensor-position hourly associations")
check("unique_S9_target",length(k)==1L)
check("heading_sequence",txt[k-1L]=="Hourly routine analyses")
check("only_S9_break_removed",length(xml_find_all(p[[k]],"./w:pPr/w:pageBreakBefore",ns))==0L&&length(xml_find_all(p[[k-1L]],"./w:pPr/w:pageBreakBefore",ns))==1L)
check("13_major_section_starts",sum(styles=="berschrift1",na.rm=TRUE)==13L&&length(xml_find_all(d,"//w:p[w:pPr/w:pStyle[@w:val='berschrift1']]/w:pPr/w:pageBreakBefore",ns))==13L)
check("93_references",sum(styles=="Literaturverzeichnis",na.rm=TRUE)==93L)
check("author_affiliation_block_exact",identical(as.character(xml_find_all(d,"//w:p[w:pPr/w:pStyle[@w:val='Author']]",ns)),as.character(xml_find_all(o,"//w:p[w:pPr/w:pStyle[@w:val='Author']]",ns))))
check("AI_and_declarations_retained",any(grepl("artificial intelligence|AI-assisted|AI assistance|generative AI",txt,ignore.case=TRUE))&&all(c("Data availability","Code availability","Acknowledgements","Funding","Author contributions","Competing interests")%in%txt))
native<-read.csv(file.path(c,"evidence/native19_identity.csv"))
check("19_native_files_exact",nrow(native)==19L&&identical(unname(vapply(file.path(c,"editable_tables",native$file),sha,character(1))),native$sha256))
check("integrated_HTML_unchanged",sha(file.path(c,"project/html_round2/ZaunerEtAl2026_NatHealth_phase3_brown.html"))=="752ee27291e7970d28fc369c1ad3c396dc8894f483aa9864e65b9edea638df17")
dm<-read.csv(file.path(n,"evidence/dispatch36_preflight.csv"));paths<-ifelse(startsWith(dm$path,"/"),dm$path,file.path(root,dm$path))
check("36_dispatch_inputs_unchanged",identical(unname(vapply(paths,sha,character(1))),dm$sha256))
cm<-read.csv(file.path(n,"evidence/prior271_preflight.csv"))
check("271_prior_members_immutable",identical(unname(vapply(file.path(c,cm$path),sha,character(1))),cm$sha256))
proof<-fromJSON(file.path(n,"evidence/patch_proof.json"))
check("final_DOCX_hash_unchanged",sha(new)==proof$output_sha256)
result<-do.call(rbind,checks)
write.csv(result,file.path(n,"evidence/final_structural_checks.csv"),row.names=FALSE)
write_json(list(status=if(all(result$pass))"PASS" else "FAIL",passed=sum(result$pass),checks=nrow(result),main_sha256=sha(new),xml_sha256=rawsha(b[["word/document.xml"]]),zip_members=length(b),changed_members=different,scientific_computation=FALSE),file.path(n,"evidence/final_structural_summary.json"),auto_unbox=TRUE,pretty=TRUE)
writeLines(capture.output(sessionInfo()),file.path(n,"evidence/final_verification_R_session.txt"))
print(result[!result$pass,]);cat(sum(result$pass),"/",nrow(result),"checks passed\n");stopifnot(all(result$pass))
